// File: 'backdrop_dyn.spv' (8088 bytes)
// Exported using binary_to_compressed_c.cpp
static const char backdrop_dyn_compressed_data_base85[5555+1] =
    "7])#######0=foS'/###$vB8./Dc>#;K?D*F:-##06'N(blZw'T1NP&v97G;)37n9=4in1H)Dq1?(VkLcaKM'Z#p*%SDYm'7(VV$J+fa+<Rd%F4<7rL>_`=-+S,<-*5T;-/5T;-55T;-"
    "95T;-:5T;-;5T;->5T;-?5T;-C5v5M/$S/MK:3NM]@,gL,WO?/P*;LFAH[rLK:#gLOlXU%/%vLFe*?[Ap2JuBw`poDvQDTC7d'oDo#a]A/f@jFfnXw0g]tS&2cWh#&WnmDY[`-#3O;=-"
    "0FD=-)1m%.@WEkN`O6##^5tFH&]j*%7:C#$F#F>H#M::)I[b?KIG:;$OV0$H^ncsB@7fFHDeTw0C.=-vKa;)FV_w'O7A,gLDXqjEMJ+[K*,^;%HW2dE8k:qL2`VV$;b7kXn1:2Fob#rL"
    "CGAEH6Wn-?T735&RnXh#,R^-v>@]PBTeoKu@XR2(Phk-$%2pgFS&gGMAD;=-EAlwMZJH##-Z8d<99VqLVQx>-B>aa-p:&:)Yn)F.VYu;A2QWU-%@5W/agaNE/fV.G*A5W%nfGb%sRep'"
    "En4[$4=7fG<#=sLgHPGMMv_x7T66Z$P=YSNN8F>HEi%UNTpR3Or^vE72NH[A1H&^ACq-nMi^`=-X<xU./oVMFUD#hLuSQ##U0xU.(&V*HDo[U.2`($#jOlt6uP>LFq(vhF^0m[A6%&jF"
    "qfpoDud[mDI4qHFU/orL5r)$#hsF?-qPerRkv'w->R=5T@XY:C.?24=WM^-Qo@.x0t&t;-5LM=-f9.FN`#/qL:C;=-Y=P)NTleq./r68%5Ut9)>4?LF@Exn*BCZt(<hq>$<(Ib%3g'<-"
    "14)=-s-'O0(P@BIj'Z[A49/GM+D3mL:&TiF/C$i$/LHZ$*Ecu>F2t>H*HkjE>fr=-d$(w-k@nqL_'$A88<HZ$M8QlJ>tpfD'4HZ$g^RrQov;aFlE.:CvJI&#-YpoSj=IkOv1I_&E5[RM"
    "M/m<-NTCq7HY@_8o.(`82)]mD04C['t4OP^JtOmB8tg%Ju5QD-g/%*.&Sd&M6>>fGZXi-#WTjumBm<#H<C<UDPV:;$+I:F7Xvm?8tqT#$XSdw'Fq;2Fejdxu7ta-Z7A^l8Q4(m9VZ`>$"
    "<n?v$.*O2(g$C2:`ZHb%@(T;..VWh#:kwu#tIX&#blZw'L'dA#D.9v-IDhk+w%f+MQopcN/@GGMF&=+NQkBH%.$=_AqA8R33C_>$Ln(^#E4$W%9:C#$>68p&xA8R3o47F[qV&Z$ZfhJ)"
    "P<@v$)91lO9cA:)cVc_/rI-^O-?.FNqf/ZPm-m<-O@;=-xOP8.n5>##B8dG*^+W-Q&`O&#P`sfL<?_*#j:&:)_Y6F[=t<;$8p?dFEV0,N--hH%ts*:)Z3<p&sNiw'OCt9)AeL#$=$`EN"
    "Ox)J%Rjf9MS1Qp7KFd9Mb)*:ML^x;-SEw^Om&4CMA>J'.r8+[PY,m<-O@;=-uG^s$A/X,M>wRiL9_YgL<,+JMdIH##w'mw'I%+x'`s3.-]1Rg)-fqr$[O/F.xRO&#A(m<-6(^,M24pfL"
    "QC?-NEkL)NJpIiLB[`=-/(m<-'G5s-rxefLrqJfLZ4$##@Ag;-kNp$.Tx*GMnN&/N/Fl(NxA5&#8T%RNqY5:;C?Ik=H9&F.SVJk=/^C_&*tj-$;dIk=3[vV%P.x],9LR2(AsL_]h@vu#"
    "o=[w'/LXw94mC_&K4X>-O&T5't+(:)/]5x'>(5R*O6e--8a,F%>Zk-$1`g-?;,D_&:[7kX2LjJ)J*)'#DCvu#o%D_&;&b-?3@'.?\?2b-?<WkM(=v%?7<d7iL*rJfL:qIiLJ-F+N=ql-M"
    "sW%iL.4pfLD0;.Mk+m<-[E.FNQ+2]PJ>b+NnpJ%#xD&,Nn.gfLsW^C-@M#<--`/,M+xQ2MKDk+NT0`EN3D:@-]'/>-6xS,MJ+m<-WqRU.8/5##N4`T.JGY##XxS,MIP',NQB:@-N3S>-"
    "m0C9&U%E_&4GNx'V(E_&Z>O0P=/u;-lRG-M=2oiL`j?lL=OhP82.q>$NbPd=Uwnf$6/'58pJ&Z$a2iS8n;[R<xN^w'tQs-$#K_PBfibDNoLO3N=E@*NSk'4NBpaBO?q$tL6?nAO`i&7N"
    ":sJ%#B]O8NhMu(NGcG8N:VRFN1QKvL.u]+Mr=`'#QD:@-#TG-M4J5s-.5FGMun#wL)X^C-xKSb-.oi&-#x49#&k,tL4QYO-[F6L-B4m<-Gk_68;%q>$#epwKL=tY-Adh&,HiKS.e]YD4"
    "VC9F%IVD_&FU1p/V8u`4Y[=#-GI5s.T_P8/0=?v$I[lS/m]Mcs#LQ50)Ht;-cM#<-imDE-a8WFMYP8NO'g&V-.YS>-$Nm<-0Nm<-SNm<-sNm<-/nG-MQddtP>CuCN0B8#M&x'kLT=6-N"
    "Bf7iLpCj*M'(1kL%2K;-)qM>Md+:kLInl-MTkG<->p-A-f@;=-&6T;-v=RA-=QF0MXX[F%LLE8AQidG*d,fw'UUaSA7en;-WxS,M/%`ENdlT=#(UX_JY:l%l]qH/2Swt-$RY-F%Mh6kO"
    "(0,F%O8l-$Dmk-$tBX]Y)4I,3jM^G3+F*d3$e]k+`[]w'kcQ9iBsL_]W]p9iCEUs76V8MB6+A5BjZM,M28T;-$0;.MOA=3N$[WmLH0;.M;b`pLK'vhLx$g+MQ_D6M52jE-,(6*Q0^8/N"
    "(wQlLt2]jL.<WuPCHx:N:-elLuBj.NfdB=#BnEGO:-elLd6wlL@nl-Md0D9.x+,##H^&:)rwv;-$X%3%xRO&#GcEB-g694MYWNmLhNEmL#Fl(Ntm8NMt:#gLn5$##6IDiL&I(DNVhjmL"
    "M0;.MPhDB%u^u9)SZXk+s$:_AdRbRW*nC2:tQ_M:oD._SiR/s73;[MC9F=2C4cq;-P0d%.[4+gL7RX3N5P5W-d?GW/7Xb3N&5H-.fLkGMU:SqL:N1=8;O4_JsJ#_fpVo?I13%*NWak3N"
    "P)2hL<q04Neu@Q-3SM>&>(5)FVgp--xN^w'dN&<-uoH6%;,9)=Y(m;-Lw5pLOLZY#U='DNU^vLOau@Q-QA,-MrQO;.f;G##;7):)*]?.6&(U.6$]3l=X:,S*'EC_&Y.v;-S;#-M'b./M"
    "XC3mLTaE_O7r')R0/WMO=V^`O?^)^825/F.b4<dOHjQ5N%8u8M`$S/M6pG9%_VX>n+E1X8-K#sIsGB8Jsfq--mP^SJQjI,M[PD6M[pQU&CP8F%WK)j:/cB/;_)q--+(?,<:uK,Mv6OG%"
    "N4.?eC[fZ$w%f+M9W54M.YlS.u15##Y.4CM+^2j;NM._S5&p`=Ow5F%B/C;$_d^w'qFm-$M`u;-Hk./MA%,G-VA;=-Sa/,MfF9@%Psc$'^RrlKb<s;-<d5=&Tjew'A#::;WS4_J+BQcs"
    "9fZk+TKAq7BE3/Mk-.EN'-,OOw,w.8YVjfMSD>R*S^0F%LHH:)X/H_&bol-$N6o-$#xKWSTPwtL%q,D-Nv)M-cVZ=Ml]3uLLnl-M&d:ENqxb0Rr(l0RcHl$M]#k_Ohs6=N6Sw78Y#v(b"
    "Ax^f`G8Uk+M[%<-)mSO&Tp`JsSiQ.8s5/F.=/u;-Vml-M8Gp;-3O;=-@4D6&bn5?%=rU%MF[`=-`61Q8uNR]c/)5EN4(Pp7os(&P:0>F[a=UF[VMZF[^(1F[B7lwThHAdX[#S/M@Z]C%"
    "Lmu&-;IlDNH5,)8=mF_fk@x9)w3gS8ld&pJCQ&:)^SApgwlGoL-%0H9ZXk]>+p-_]8<4#?SD>R*k-N>?o*:F%3Owu#Gu`w'<C4'-&`l)88qm--n1aw'-Y8)t+a$8@p,7F%B/C;$g&_w'"
    "RwY&H-Y72NP%T,M/E9vLobgvLU:T9:h'12UioOPT'PllTiuklT8A0m0k1LMU.;3GsM7miU^Br,M'1HwL>C;=-Pgh9MvO&+MW6u8MTTRFNR9QwLFxUa8bldfVO8>R*N^gd+w5=ROKI`.M"
    "'n.:NFp-^O=u.>->-OJ-)Z>1%2b&)X`Q6F%T?oxc<'#&YOw5F%?`P9i)faw'Kho&-%*J:NTIlDNB*i%MAUos8:wNYdL/>R*[,#<-ZJs>MF+m<-Dvj3Mt4t;MUgK=#o-Uk+H.NVe8qacW"
    "7i(3;Q9pVOEI8C%RN$:)e<0,N:+;DbA3o;-KhG<-Rb/,M+WZI%Q3cw'@cq-$W$xwBv6_&H*Z#9%W^$:)#N6'-v9QA%^Kw&?Nkw&M)_iY&iWLp^WGkGNI(='MS'vhLNWMrZv#t;-cB,-M"
    "UCFV.t7>##_$]7&g7XfiKj&:)A#cY#*.D9.f;G##CK15g$]1ENBP#<-<gF?-YwN$%[lX_J-&3?.&s&V-nml-M$B6I%Gkbw'TZp&?og&S%*o&=(hiZ]Y/,lp7RYtxYNlk,M@v:Q&80Rk+"
    "5?k-$?qf_8-raw'F[g*%2(*,8TrpuZL/>R*V^x;-%ou5&=pQV[Kj&:)IX*kk/q>:;cOR&Z=O;=-q?2+8>)5DkSD>R*&6K<-tcA?MP9gN-aK>1%S%1.?f2%:)&Q:WJgc.YOWQrP-vml-M"
    "TDrP-5&d1%i;%:)kt1AlOvaDNC.q(M]Kt'MBZkV.e5>##q<#-MQ=PG-#+Wr(oC2x^_@4x^u5Ae=WGkGNIKH)M]#k_OjRQ)MKxrqL$1,GMVrl;-xB,-M50sxLARx;%jdK_&/CWk+U/CPp"
    "Kj&:)lk[lpKj&:)xRO&#N%kB-kU,<-e7T;-nKqS-jTvD-Ov]h:?Hq.rL/>R*#DH<-W<4CMIt9W.lMc##)[`=-qJQD-,Dv5MdLihLxh+CN@Gp;-ok)M-/tRU.u15##w+Qt$LDUk+Nn`&d"
    "=t.>-FT`.ME]9=#ScR+M=(:l8O7J`tS-6F%n1t&#$&>uu*Vd<-=kl-M7BSYMkG?##:L,hLwU/+MCI`.M-.gfL'Js*M^Q#<-rO#<-2,Q5MAWvD-dvNs7>c`2M':#gLjBnR8uim--%JZ*7"
    "8e*<-,]Zu7.:Z;%,VxJN6qU)N`$t_&7Ps9)&hj-$muG<-4(m<-6R+?-R`/,Mg$Os72_rS&ZMI_/r`'F.i]#<-PE`.M0/hK-9S,<-/sm*M)ScS.N<G##(M#<-Jkl-MF7m<-9(m<-<.GDN"
    "u)2hL4qugLD0;.M1(kB-IRG-Mq<*mLWJs*M:VCq7dR0j(Df-=-7G*g(FXp&$BE`hLh07r7hwG,*J`k,Mg$Os7etcG*ZMI_/=;C<-9^?EMVUF0M/@QA%$ahJs)P#<-t48v$GAOd=#9T8%"
    "H.t9)LW`Jsxt]+M#=.FNp=5L%*p)=(B&cY#9CS;%@-ew'6U2:DeF/s7n`mV71Tmr[`BeDN&B,gL6sb;NElRR&?9`R*:2:.6iDW.6gLlw't<&@%Mu'kL.af#M2C;=-2?Lm8RkIP^JRs'm"
    "wd^C-4894M4Q#9%<b#:)*E1lO6%f$'3XXw9l*di_M,?kOatF_/J`C<-JK+8&4kw;-Nml-MLd7iLZr-A-t#T,M'r,A%i67K3(G;pLL1$>#4cGlLHdMM%v(Ipg=pIiLGiK=#pjQiL0wfN-"
    "f&l?-DfG<-QFlDNe-fiLB,fiLV%HDO4@,gLF2oiLO8xiL)VcS.dMc##GS,<-O@;=-?L<NM,S-##x(G>#]*@>#w]AXu.c$+#";

