// File: 'backdrop_dyn.spv' (7948 bytes)
// Exported using binary_to_compressed_c.cpp
static const char backdrop_dyn_compressed_data_base85[5515+1] =
    "7])#######NJ.p&'/###$vB8./Dc>#;K?D*A+-##06'N(blZw'T1NP&;.l+D)37n9=4in1H)Dq1?(VkLcaKM'Z#p*%SDYm'7(VV$ES2-*<Rd%F4<7rL>_`=-+S,<-*5T;-/5T;-55T;-"
    "95T;-:5T;-;5T;->5T;-?5T;-C5v5M/$S/MK:3NM]@,gL,WO?/P*;LFAH[rLK:#gLOlXU%/%vLFe*?[Ap2JuBw`poDvQDTC7d'oDo#a]A/f@jFfnXw0g]tS&2cWh#&WnmDY[`-#3O;=-"
    "0FD=-)1m%.@WEkN`O6##^5tFH&]j*%7:C#$F#F>H#M::)I[b?KIG:;$OV0$H^ncsB@7fFHDeTw0C.=-vKa;)FV_w'O7A,gLDXqjEMJ+[K*,^;%HW2dE8k:qL2`VV$;b7kXn1:2Fob#rL"
    "CGAEH6Wn-?T735&RnXh#,R^-v>@]PBTeoKu@XR2(Phk-$%2pgFS&gGMAD;=-EAlwMZJH##-Z8d<99VqLVQx>-B>aa-p:&:)Yn)F.VYu;A2QWU-%@5W/agaNE/fV.G*A5W%nfGb%sRep'"
    "En4[$4=7fG<#=sLgHPGMMv_x7T66Z$P=YSNN8F>HEi%UNTpR3Or^vE72NH[A1H&^ACq-nMi^`=-X<xU./oVMFUD#hLuSQ##U0xU.(&V*HDo[U.2`($#jOlt6uP>LFq(vhF^0m[A6%&jF"
    "qfpoDud[mDI4qHFU/orL5r)$#hsF?-qPerRkv'w->R=5T@XY:C.?24=WM^-Qo@.x0t&t;-5LM=-f9.FN`#/qL:C;=-Y=P)NTleq./r68%5Ut9)>4?LF@Exn*BCZt(<hq>$<(Ib%3g'<-"
    "14)=-s-'O0(P@BIj'Z[A49/GM+D3mL:&TiF/C$i$/LHZ$(3,>>F2t>H*HkjE>fr=-d$(w-j:eqL_'$A876?Z$SoIfLA=McD7eHZ$b0v=Pov;aFlE.:Cit/F.c9:F@H(2/V7IbMCe%cSM"
    "(hDxL'5WJ%d+suZ6Ri;Ii#AuB-`g9V>9iR**JcdG<*NfL[F?##V)MeMpMH##M?%q.-</YBa-IkXYq3F%:4mHG9fKZ$gk<onu%xcEKTcd$<nL+rJ/=#H'cew9w5L_&$km>$.hLe&DQHk4"
    ":4Lk+$bj-$.*k-$=[JX12`Nh#Adk-$h$:m9TE3L#G5YY#hgv92#w+F%@ak-$>bh>$++m<-Q:m<-/.m<-Q9ct8?e>:;G[):)q+(:)N&1`/?cv-H>(g:)5VA:)B4g:)C@i-6-m7R<Kgb_/"
    "_V1`/8`A:)bt_;%Nr@&,7j5?I%HqDMug?T-)QqDMK8xiL/xSfL;9U*#dldw',86:;n?-C&@BN/M%PP8.qAP##iN_w0q;Rm96bfi'Odo;-1HKp8*xV:Mp-3:MbAs:ML=tY-^C*.-vxe+M"
    "7'v.9Oe>:;hc;KW7p+D%_&lJ)/V,KE59MhLR&g?Mq,MeMWMH##u2i9MK8xiLE7(p7o@7Ks)KvD-K@;=-)5T;-U*JY-=dYEnF]%a+O=tY-tNG_/a1;;$fxZw'R*h*%3FqhL/:#gL7C;=-"
    "&M#<-j?S>-9L;=-TRG-M7:#gL1F5gLg>5&#u(B;-2_.u-q&niLx'^fL=A6##0F;=-j4m<-6h7:.K`($#T_Cv$>+CH%$;Y8&x)`w0#2>s%2t7p&?E&:)7igw':fA:)GdIwB6sC_&Jw0B,"
    "5_fi'Kj&:)r:qP'C9ew'cJ>_/`@SR3/LXw9;*8p&G>-g)P`H,*BrW>-1tfE[3U/g)G^&:))Gg-?X2P_/h2SY,9-(,)C9ew'0:3j(BC):);ugw'C+B:)v-w;-D(m<-t5ZD-I;8F-F]&GM"
    "oLwA-B(m<-0`/,M+xQ2MEv3+NB7m<-QLm<-NX.U.>;G##8b^C-3xS,M3']iL#xSfLD0;.Mk+m<-bE.FN%$LDMqcB,N<@,gLPa./MO]9,NnW&%#w><jLtVP&#)WajL.iG<-R)Q5M_?VhL"
    "%2Z98NVE/2(o'^#cpaJ2.OvV%%>6?%UOqkL-2K;-HtfN-ZS,<-S'Fc%4sES7VBa583%q>$7e7:;x=rR<OmK_Sow6&>*lbxu&e1R<X3Z&HfXwA-<5m<-M?S>-B5m<--n^C-LgG<-:@m<-"
    ",)qk.>;G##J-hK-aUwA-[pg<Mb0iH-kA;=-s7pr-.AXGM0,kuLLnl-MwIr'#3F;=-(ml-MYi5WMV2$##^_[T.D%###Wa/,Mw'sAN(fn*NvCJBNgQbg$>$iFrgBiw'B$qE@`o,##2Lt9)"
    "x/-_JF7T;.6oWh#G&1I$rGf--A&-F%S78`&Pxi_&(0,F%Epk-$HN[3OLiH2rbH<mLfgJ/Na+elL'.m<-dlG-M[3@iP/UwiP+H9kPNqxnPn+=rPr7oYO]OXR-:ZS>-)7m<-Vg'S-QfG<-"
    "V*gN-<M#<-Hh'S-]xS,MnU/+M<v.>-c@,-MkbeBMhNEmL4i?lL4A2pL=8X+N?=*mL#`_68]OSF.Acg--^;pF.iBGG.9wmd=H]XjL#RE3MUvt;.u15##[C9F%d'i9Drx>_/OKaJ2t,8)="
    "WkCv$Sa&g2DFP8/.VWh#L<s9ii^ZR***o9i/E=:iml>)4Kj&:)c(T_&2UJ8A<bVk49tsr$k2_w'`w*WfCnl-MWv^(MUIuG-F(/>-txS,MV&5@M*(vhL.%g+MQ_D6M52jE-,(6*Q0^8/N"
    "(wQlLt2]jL.<WuPCHx:N:-elLuBj.NfdB=#BnEGO:-elLd6wlL@nl-Md0D9.x+,##H^&:)rwv;-$X%3%xRO&#GcEB-g694MYWNmLhNEmL#Fl(Ntm8NMt:#gLn5$##6IDiL&I(DNVhjmL"
    "M0;.MPhDB%u^u9)SZXk+s$:_AdRbRW*nC2:tQ_M:oD._SiR/s71)%mB74]PB4cq;-P0d%.[4+gL5FF3N5P5W-d?GW/5LO3N&5H-.fLkGMS.AqLUF'@8;O4_J.'[-Z`@LcD5RTJDZMI_/"
    "C4aWf:k'4Neu@Q-2SM>&GO%<-VqI3%3j8)==)l;-Tll-Mel1T.%)###7h`=-j9k_O>g=rL?X+rLBZkV.f;G##=gG<-Fa/,M^@RA-$KRA-;_:ENVd)MO3xSfL(Q#9%CEG_&9Ln-$G2Jk="
    "fUE_&;Rn-$hh1#HpqL>HpiJ,MFdCx7hoaYHEm=_ACZ1F.%b?pg('>w7B7_M:h5]R3R0ZG@'C_p0KH`.M@i$R8.M'x9'@'x9hK8#:$nu9)9Kk-$$#''-1j-:9)<Ep^MIH##aP':)g5&g;"
    "-h:F%iq@qpL0[a.u15##CR`.ME]9=#PN+oL$NpnL_@RA-Ek./MA%,G-RA;=-Oa/,MJSXO%Lgc$'Y.ZSJF?o;-spTL&Tjew'=m9:;WS4_J*t,x'2Na2i(9T8%]Ft&$T0iH-#;iH-/fd.%"
    "Zfw9)anniL<=r%cak3/MjefS8J(RMLxjpuZ`4m;-d;#-MKWa6NP35OO4v.>-jSG-MRfK=#_GL_&aS/2_m]JM_nffi_SD>R*ho+/`%sYk+0]$<-@B;=-:b/,M45NJ%ESd&ZE6S>-Lf$R8"
    "u[#,a;)O,M@Q#9%Cw#:)F[g*%3SJ:)QYXW&e)E'8hsu(bSD>R*($up'Wnhq701Xwpw1xJN%dSC8kH,)O1AZk+*FKDO-i>-Me<.FN?X1x7R85F%4jd`O=Q/EN[kEuLF[`=-txS,MGG:sL"
    "H<.FNl%gK%'e#=(0B:K3$5V1NenGoL=c]F-&gG<-M2$M&Z^s-QfCWv6_'v=Pf)@>Q]<A<-g93FM#>0vLBhRU.u15##mi-2ME]9=#Y/(pL5xEJO'N%2NBP#<-pb>1%nIx9)FE>3VeUTvL"
    "dIBvL6[`=-dN#<-S&kB-MM#<-$g`=-QGtJ-WtVF&#GPPTKj&:)Bnc9Mw(j(t')-v?ZNAR*R&tlTANgE[9+I<-u<J'.f#->8<0LMURBXk+uRhiU*^7F%SBXk+>RM-Q-wU'$=t.>-N_F0M"
    ">t.>-V5/>-AS`.Mo=a*MBQvwL6L%+8d^dfVS-6F%B<]`b*(A_8GEx%cL/>R*?-x;-UJs>MF+m<-?vj3Mt4t;MUgK=#o-Uk+CVqxc^@X9`lkD<-*wTx8`jNYdSD>R*fhck+T^f;-FhG<-"
    "?7T;-`kF58f0KVe2KIk=W$xwBq'_&Hdb?Q%RN$:)WA<'$`b?Q%Bx1WoILI&Mi0Wj&dHLp^WGkGND`e&MS'vhLNWMrZY$s;-OnP<-Ob/,MZcB=#;i7088LUk+T<cw'+JjcsSue+M:XX)#"
    "U<<-v*ag2MWm./MrO&+MNL%+8P65F%r5DMho9.ENC*='MjBnR8W+;DbKj&:)N%Qp7@s`cWbJ><->BeB&=/u;-rnu5&dI2?%=KK%:X3/F.T$'&YSD>R*xRO&#tI^s$&Je$'=`$ek6'o+8"
    "(LUk++law'(8Ncsj@T_&Cb#/iL*3ENe&)XO$TYL%^p$:)_5Q'?_2;XO_U^`OnP,18:5/F.T^VcjSD>R*G7p&Z_DVXOWQrP-qml-MTDrP-p,h%%d,%:)fFTcjOvaDN>fB(MR>Y@MO[X)#"
    "5_J(MP<.FN0%m18Swhxl^'t--ls3>mJAO,M1rEB-xml-MH9gN-dnP<-db/,MfoF[9?w);nL/>R*Nw+'-d>6)Mb,q(M[8-)Mj:6L-p$T,M9WvD-#UG-M5P5W-.%Qw9fEOb%`kr-$nSvEn"
    "jP@F@voI:)%.E<-$C,-Mpm5a&DI[RjS52F.:'98%Y1=R*lLS.?w(_G3k-&RN8a,F%1@;.-wLF&#cuv.r0Y8)tq&.crTlF,M>t.>-/-22%0PNcsOw5F%B/C;$YVdw'l9s-$;#u;-Cm./M"
    "qA3U-*C;=-[:gS''adw'1qx%YbvV#$Up4F%ol.DtB*Xk+*cF]u*^7F%<&n(tW]Uk+&QexuVWJQ8Kik&#$&>uug39v6F_H,Mcn$78)]bA#<1#KN,(^fLdH5x'5VA:)muG<-@kl-Md$t_&"
    "3Ds9)`vx;-5:#-MlU[F%+4K.?A=#KN-F5gLi/FGNF<3(=o9q.r2cWh#WkjQa)9Gb%KZ=_/&hj-$9nV8&prg-6u'%T&3e;s%Cj=R*?'Yw965[w')qj-$GM9_83]gw'=;C<-1G*g(@Fp&$"
    "P*@q7iUO2(SD>R*=;C<--TP5&3jC_&d1q&$<&tBOg<ts7e[K/)8mXwpVpdw0O0Od=.M+48V85F%.Z'<-/5Q:8m1p&$7E`hLlTN49mim--3e'x9HO%<-(Lr9.u15##hLP,M2+m<-Bsi6M"
    ":nt)#@=;mLGs>A:r?5F[0#[w'9'`R*NlC<-H;;.M,BRA-rv-2MgWG-MftlhLqSQ##NS,<-2b/,Mk1tuLrp&S%=3`R*YpjDNwsb;NP+]F%[2RS]SD>R*e;no]L/>R*)52F%gR05^M,?kO"
    "atF_/J`C<-EK+8&4kw;-Iml-MLd7iLZr-A-o#T,M'r,A%NGu;-4S7U.x+,##4Xk]=GrP,*=hYhL4QrhLGiK=#kK$iL6UO)#uvdiLG^.iLCvRiLQ0iH-BS,<-H@;=-VX;=-,fG<-I@;=-"
    "QxS,M-=+)#&?<jL?pIiLUiK,NHi4o0?&###x+,##]),##CgS9;5F%##";

