// File: 'clip_reduce.spv' (7076 bytes)
// Exported using binary_to_compressed_c.cpp
static const char clip_reduce_compressed_data_base85[5090+1] =
    "7])#######8<2cW'/####vB8./Dc>#;K?D*MrNcMVEj$#2_e6/.f1$#28^kLIVjN;e/W$H_>Pe3oCA['TxL$#4(gGM$@W$#f.xfLpu2*Mn6T=B.cj*%<tvV%0tR5'0<0j(7&D)+<Sw],"
    "?osY-@x8v-C=5s.DFP8/EOlS/.*O2(s&k-6i$115#w+F%'1Qv$X_j-?..u&#Z9'##<F5-MMCFV.'^TSD9GD=-M8q8/W.v-G%j*SM6SME/P*;LFAH[rL]:#gLJE;=-k[Rv6vCM.GlouhF"
    "qi1EH$3a]A3YHlE#87FHuOw#JT/orL3MH##i+:1M@E:sLBjh9M+xSfLW>sMOZL6##x]Gp2PP:@--(m<-P/m<-cOwA-7$b30(P@BIbQM=BSLJ_/:X$Z$U]k>H.GI+H.IUwTQM):2pxBEH"
    "J'ogF:ufw0T735&FIXh#GJ>p&75mQsPq[$0d/cuT&fBK-%u?mL*fipLO[Z##eldw''EC_&LG)FI58nw'T9htB[e?IM(SQ##k&]I-A'47/*)%bHDF+qU$ZZ##$.Tv.x5FVC+E'UrPcUV$"
    "$qFkOnF,Z$IKdw0e/&oDE+R.#$-&F.f)i`J=IxlBKh&TAngluTHA,gL5?b+Nn`&GM2Dgr-dldw'<CJqDcgv%+kFc#HbHwmDngZw'iASY,I87[^/LHZ$I]OV-%<u;J3F`t-<E]88bFLVA"
    "t)/YBe^[mD0QJuB'>ZhFjE.:CU8L.GdUS_/mxl_/P4Lh,3_>_/t=-5/rk6<I-Q=7D@+8/G#,1T&+bw#:)^rTColOoM^kkjLtI^g/nrY1Fn5xUC*,X#$8_t9)Aen-$OMuu#-J-F%Nsl_&"
    "RY-F%@BY_&0Hiu5x?XsJRXQ##=+vlLl0CS-C;#-Mm<*mLX4iAM`kVV$gi*87QYK;IC(W#MSXQ##B=;mL,WnoDA'r2NK%$xLfp*J-$gcs-Ej*SMS&m4M&OT]A:>LSD>oH;@Ykek+*&K#H"
    "IgnNN,9RtL7@]qLOXQ##cvJ8O0gw^MY#5$MMR4s%bYQ%b<4]PBZ)A,Mr4@]Mk^T)&Suiofbe/+.HmjxlFa%aF2W[W8Uq)$#65pS5B(8fGcpJKFuC@fG)>2eG$3p,Gbd3nD^^Ik42V@rm"
    "]mc6B,,iEHj,]:CtlL*H4k@u-=-,)M5nP>Ba3CX11J00F.i[K3q5gNMrs@jLXrc59$JF&#4(cA#6C_>$l3:m9UH3L#KYqr$.OvV%O+/F.?GpDNo6U*#w:#s-V@t(NKxSfLD>+jL/]&,M"
    "k+m<-RC2X-dldw'-;6:;.B,F%A(T;.0]j-$G[):)x5O:)HjTw029KRNFwC#$K-M_&K*`>$BZO2(xV&Z$F)hJ)o,mER-?,F%$bj-$]-[8&;H>wgkV_wgX_HxgL=tY-/(cA#qJN#$=$`EN"
    "qvG9%HINh,_:._SRN^&?Afc*8`84m'%t*:)[<W5'sNiw'OCt9)AeL#$-=Mt-jx*GM?wG9%ts*:)-v8_J=t<;$+*2?%A2oiL-Q_99Q1fJj@vNbNWMH##v2i9MK8xiLE7(p7n(ew'?>V_&"
    "lckr--_rS&:A@&,Sb5s.I]%a+TkP8/HS`D+UtlS/Ko[A,7d,g)hEDv$BrW>-.VWh#2RZ;%/rbA#@`w],?q$Z$S7/F.)3,F%f@vu#,oF&#49`&#ioZ&Q'FPGM'YH##%####*5T;-w4T;-"
    "*'LW.%####-`/,M#E5&#eXbgL9^&ZP(eC)N2_,5MeCLw-bqg)N44oiLlRGgLL0;.M?^,5M8-7aNKMH##,Cw2MZ?,&#dq0hLLnl-Mux(hL:O.U.G;G##ac_@-1og<M;9.*NDKihLmj[IM"
    "c6$##^&l?-K:#-M.4pfL@&]iLDp*+NO1;.M>F`hLLnl-M=@VhLDUG-M@_e*N7ol-M,-m<-6CNM-@CNM-XmclM;d@:.@vrx+E]%a+V@/F.q+GkOdp;A+&u^>$98%a+E5kw'KCB:)l?Y>-"
    "'kx5/C9F&#tvdiL^tnf$+9iu5Lxw],Sj3x'O7+x'(;xV.,=?v$w_B#$l()F7w:5OO3`=R*iPfw'T_B:)Tb5s.]kP8/&M)F7R(j_&W4#:2RtlS/WbBZ-Tk%/1q/H&,=jp/)bG.;6KIBZ-"
    "l.bo7;_L_&F5-F%#rWw9RW&F.sWu9)fRv;-ofG<-4@m<-rx(t-[%+GMh>TnL63%*N/P:@-0SG-M17m<-#]sM-LK:@-7xS,MBP#<-5;#-MjPG&#[;:pL7C;=-LxS,MHcn#8xw''#GR;;$"
    "%p-x'J;Kj1Txe+M[_4rLXotjL0_AN-X;#-Ms>[tL#RE3M$b[I-bA;=-W'P8Mm%buLIP',N=%6wL@,MP->4m<-&6m<-dV:@-$hG<->BS>-OAS>-94m<-RaG-M4%iH-W6m<-;r:T.C;G##"
    ";H<7%se.F%n_VV$tl8WJ9[`=-#oEB-M::1MPgEB-t6m<-jo?x-J>RBN/c6lLSNWU-bRG-MI%1kLkqVu7)shP0Y6.m0#8scsRk@J1t,8)=Mj5K3J4$##$(4,%csE/2h]7I$?%h;%CgF?-"
    "VfG<-O5T;-D5T;-Z`/,MsM:@-](m<-V`/,M5O;=-D%FB-aa]F-qkl-Mct.>-`M;=-rkl-Mc=UkLc@RA-Ob^C-7X;=-_694M-e^C-ukl-MumwFNNuQlLT0;.M$_:x7EXq]5dS>)4G8Uk+"
    "p6<-vh%`&5Zd5A4wbR>6n@7#6.VWh#FJ]p0EJ=jLh)PGOm/YGOjgJ/N,@,gLwQSv70LJ88.3V&Z;Se>8E%[#6W7FcMU[NJM4KQV[v:/p8jefS8t<^A,txVGslF#292cWh#E&v92([cP9"
    "Ha&:)g^6kXiR/s7]<bSAZXRML7&D)+Ct4v6dDfw'Grqw^bXH`ESIniL<Sw],d,fw'mcS,M1Ox>-i4S>-v8S/MRZx>-E*CPNIQ#<-d=8F-GQF0M&3Pw7#L$j:vFCp7--6Z$ObIb%j1m-$"
    "uQj-$V/.p8gTs;-8oPhL5%co79qVG<L/>R*10+?@6m_=8h:#F@/_Ts7('K]=/gSD=wt:)=w/sc<H1(Z$:IY&#sb5.-xRO&#$^)'%'Lb$'45l]>#UOAYWN3L#G6cu>&^OA>RPxf;kQbkO"
    "5WD:)PEKx0Vdpx0%:w;-7Y`=-/a/,MO[X)#Y51pL?D@#8iK)s@e73v6t1?<-0gG<-'W&0%0dF_]>s,F%)rm-$ksh*%0DW)##w.F.LQew'C&cY#ppQd=7%T,MqBj'8q@Uk+Iotk+pVm+s"
    "g)ZMC8=xlBlr5.6K76.-axmY6dJp;-v8r*%wLF&#fP#<-hA,-M%dSC8V$,)Ow7p,MF+m<-Xuj3MW6u8M*Ks*MNSw78Sr(&PN.-EN0d(POgGw=N=wWuLF[`=-]N#<-LN;=-1ge+%ch72L"
    "o>[YQfg(&PG8Uk+oC'vQO8>R*x-w;-+%g?MvC9vLLnl-MLZqm8%lScjO4u(kP=:DkSD>R*JFU`k9YZk+GOq%la:TcjG8Uk+@c#29M<1AlfZr,M8hDxL<XYL%tkYW&ENx>-Bb'-%h8%:)"
    "F[g*%3SJ:)4&%'-5=+)#sdHiLf,q(MGikjLHH`.Md[X)#_YH2N)h&S%)Y=F%;[a=-]g0x(NkN_Su_nY6OctoSE[?-Me<.FNT/X?8$65F%t)'<-S^5=&Y.v;-,ml-M/gYOMlMH##`#T,M"
    "Gh]<8*8XMC-X<<--jZL-@uI3%@mv9)+9wf;;%r;-vR/O&KBqfDKj&:)A#cY#H=up7/wklTreN;7.VWh#RIi9;lVLb%f&p-$<wNdXwNV9N-DAc&r+e$'T@OdX0@i*8A<#F@/_Ts7wC[(W"
    ")1efVq>KJV+TB<-^^5=&2VH;$qC[w'n>p-$vtWv6t4@cVc0#3)Rc(AMBv&)(IOpcEY&RGE>1r;-P['-%eP#<-wnWo8V1H;@muX?.0D;:%SV:WAsl)J%I2w9)-$s^oJQx;-Xll-MAE8C%"
    "kjZ&HAt.>-VSG-MRfK=#_GL_&%/))X18DDXSD>R*0kE<-b^5=&4Fnp0)<f:NA/k883RX]YSD>R*w'.:)*eiDN^v:T.t7>##G]sM-&gG<->6T;-DsJ0%mkSs7X:FcM+ttxY*Jq;-lV&0%"
    "(0,F%8$`R*wLF&#fP#<-h:;.M<P&+M2T-5N2:(sL:Cm<-MM.U.vOc##gM#<-`2Eu$tul4)WKZA8.H>8J6DG;IL`YSJ?E&:)l4a-?*DkwTi&hwT=#X,Mf7&#Mi9R78T66;[?92)FG8Uk+"
    "Fc6'6'B8#Md07r7tGmr[f]o,MS2PD%IJ8R*$[S'6g#Os7uNMS]^W=9.f;G##HMNS]>1Xh#-N'<-;c-D-As.>-M`/,Mf^_sLqQYO-rFq-%CBp--fi-dbv8T8%AQ*dtnStJ-V<gD8uoUPK"
    "SD>R*QP:WA`#<'8+MUk+U>`w'+JjcsSue+MwK9C-'aT_-F:0X82AC<N@v.>-H8t$%=e#:)I1qp93/G$MR@+[;GZppp<Yh<NtG)b&:1f$'1cxJNNJ$.8:7FM_WC/F.9tsr$r0J_&:dQ.?"
    "*Re9M:Ys9)Q2xk+R^F<-X+ZO-K&22%_e>RaH0$:)/rZ.6ja'e+X]j6NutU%MF[`=-d=Lm8-Wnxc@Ir%c:CR]c2Vq;-)M#<-/]euLi)F]F?^Z`*BnNYd2^8)=BZ1F.c@QF.#w+F%e&1;e"
    "K,>R*f/LVeDb(^#j8hreK,>R*hA-8fEkC#$lJHSfK,>R*IT98%s1D_&p=owKICjreKWGSf8q<<-N6c`'S9cw'Fuq-$IqG'$W?B?N>_Le&R$g$'f8T2`g0T080h(5gWC/F.`gD9r</D_&"
    "K.r-$w^w-Qp@Y'mP9X'Mc(wX.cGY##cfG<-N7T;-O7T;-+i6=.u15##6oT,ML1$>#S$5M;pl8GjRnXh#E50@IO3O'McV;ANE1PG-2X@+%Vf=:r-LRF.<1Is-DKY)MmC+ZO/9S>-JW:@-"
    "x<#-MhXvA%ii':)OlZlphg=Ppbxtc<vteG*ivt1q`WdA#a+3v6LUgw0JB@['M(:`fxrIU)g&UiqvOw.rd:<Z6LxKS.mD6Jr&,1ENQ#m6@4)g*%3SJ:)fQKLN6%gGM4@,gLqCj*ME]XjL"
    "%VcS.eSl##f#&'.:C%/Ni8W*MsbxBNp:$>#]uv(#$m8Atp.f;4";

