// File: 'clip_reduce.spv' (7188 bytes)
// Exported using binary_to_compressed_c.cpp
static const char clip_reduce_compressed_data_base85[5110+1] =
    "7])#######S+BJ)'/####vB8./Dc>#;K?D*Q(OcMVEj$#2_e6/.f1$#28^kLIVjN;e/W$H_>Pe3oCA['TxL$#4(gGM$@W$#f.xfLt7W*Mn6T=B.cj*%<tvV%0tR5'0<0j(7&D)+<Sw],"
    "?osY-@x8v-C=5s.DFP8/EOlS/.*O2(s&k-6i$115#w+F%'1Qv$X_j-?..u&#Z9'##<F5-MMCFV.'^TSD9GD=-M8q8/W.v-G%j*SM6SME/P*;LFAH[rL]:#gLJE;=-k[Rv6vCM.GlouhF"
    "qi1EH$3a]A3YHlE#87FHuOw#JT/orL3MH##i+:1M@E:sLBjh9M+xSfLW>sMOZL6##x]Gp2PP:@--(m<-P/m<-cOwA-7$b30(P@BIbQM=BSLJ_/:X$Z$U]k>H.GI+H.IUwTQM):2pxBEH"
    "J'ogF:ufw0T735&FIXh#GJ>p&75mQsPq[$0d/cuT&fBK-%u?mL*fipLO[Z##eldw''EC_&LG)FI58nw'T9htB[e?IM(SQ##k&]I-A'47/*)%bHDF+qU$ZZ##$.Tv.x5FVC+E'UrPcUV$"
    "$qFkOnF,Z$IKdw0e/&oDE+R.#$-&F.f)i`J=IxlBKh&TAngluTHA,gL5?b+Nn`&GM2Dgr-dldw'<CJqDcgv%+kFc#HbHwmDngZw'iASY,I87[^/LHZ$I]OV-%<u;J3F`t-<E]88bFLVA"
    "t)/YBe^[mD0QJuB'>ZhFjE.:CU8L.GdUS_/mxl_/P4Lh,3_>_/t=-5/rk6<I-Q=7D@+8/G#,1T&+bw#:)^rTColOoM^kkjLtI^g/nrY1Fn5xUC*,X#$8_t9)Aen-$OMuu#-J-F%Nsl_&"
    "RY-F%@BY_&0Hiu5x?XsJRXQ##=+vlLl0CS-C;#-Mm<*mLX4iAM`kVV$gi*87QYK;IC(W#MSXQ##B=;mL,WnoDA'r2NK%$xLfp*J-$gcs-Ej*SMS&m4M&OT]A:>LSD>oH;@Ykek+@<G_&"
    "HH0@Jh).A-TT,<-6ZlS.-AP##g%i9M#G:@-e2en8s86Z$)*:x'TUOgEXr-A-t&.78TGW9`Xa$:)B*cw9hvcw'<1USD(FNs-?*l[NfK;GHu9-[Ab'$[A4DM*H,,lVCdH;9CrGX7DZ#Sv$"
    "d^N_/6G'8Dqv[mDnKitB)nMfLbRQ##wv[:.2MnbHi+#^G/`_wBrwD<-B*JjLA/K;-mIre$3SJ:)3PA:)&*,F%;t<;$tIX&#bSC_&&hj-$Wjd2ra:ex-E#ffLF4$##PJ:@-#M#<-N`/,M"
    "lwQ2MQopcNVC?##CA)d*w4:p&2cWh#Cs9I$6J:_AtEW:M51(^#&tG_/24K_/5VA:)a*l_/6YA:)-`rR<7]A:)6Z,F%fZwS&(1?v$cwIRNd`4SNge-:)QV'W%n@lw'OCt9)nc:R<vxe+M"
    "JE(:9eYN-Z9@G&#*Z+:)N&F-MgYiY&icA;Mp-3:McDs:ML=tY-^C*.-vxe+MljJ%#]kp=9DvV:Mp-3:M8IPm9<B_c)<)l;-BM#<-m#v5&lsJ<-EGJ'.s>4[PY,m<-O@;=-uG^s$B8dG*"
    ".7q>$$/-F%)qj-$J(+x'SC+x'I%+x'TF+x'Hx*x'UI+x'?v,F%wB=wT(0,F%>Zk-$;tdw'5>*x'#w+F%XQe--'-,F%F9[;%AcnA,e+<X(2[F3bd2SY,qop;-V%3:/)/5##]XbgLw-gfL"
    "Y*elLoF6##QlRfL6hRU.ISl##2fG<-1YT;-9)Q5MGQ:xMtF?##x[ZL--%kB-=:#-MTnl-M-,m<--T2&.jEQ*NYeP[.C5>##HRG-M$;6L-C:#-MwPG&#g36*NbE@*Nv,m<-?L;=-io-A-"
    "TA.2.hEqhL^QrhL6+m<-&M#<-H(m<-QYD6MA&jE-MRG-M=&jE-H:#-M9&jE-:694M>X)>MD&tBO@e#DOGw'kL61W#M[=-##&f[w'@5)C&]U]A,Yeu>$rl,F%xZj-$CFD_]DJD)+psv92"
    "9F&?7Q@$##G;G##kRCq7/VX&#I0,x'PRB:)P=tY-$=ZEnJYD_&$bj-$wWj-$)6V;.S1K&#q)w92MF9v-Sj3x'[ttx'TF+x'.d3p/6KIk=iPfw'YnB:)n_VV$a]GkkB5QF%]oYY#BLE_&"
    "pq78%C7.F%KLpV.7.B.$xqiJ)-b,p8):s22k#0nL0q6AOt)9nLYn2?#s+KV-sfG<-sjp[NBB^nL?+>DN-GRIOx6V1NQF5gLPa./M##ZoL-VcS.G;G##8)^,MN>b+Nv/OJ-0gG<-,c/,M"
    "Zo*$82x''#GR;;$'v-x'ucFj1Txe+MnkFrLXotjL@j(P-Z;#-MuJntL3^,5M4mBK-dA;=-=S8F-cgG<-nJ:@-&$T,M]MI*N)$A:N?QR*NBf$=N9-r)NG.R=Nm.:1MgR^?N?E`hLk8#&#"
    "EI418<xrc<G=BZ-k39loj]J,MLp*+NS>ABNV(6=MVP]BNCdRIM&G?##If_@-IuQ2M,lkjL-2K;-K;^;-Rp&V-X(H<-U4`T.t15##OM#<-l,6u7nTX&#t7R&Q9O;=-hRG-MPl1T.6178%"
    "CgF?-WlP<-O5T;-D5T;-Z`/,MsM:@-](m<-V`/,M5O;=-D%FB-aa]F-qkl-Mct.>-`M;=-rkl-Mc=UkLc@RA-Ob^C-7X;=-_694M-e^C-ukl-MumwFNNuQlLT0;.M$_:x7EXq]5dS>)4"
    "G8Uk+p6<-vh%`&5Zd5A4wbR>6n@7#6.VWh#FJ]p0EJ=jLh)PGOm/YGOjgJ/N,@,gLwQSv70LJ88.3V&Z&A2pL1kL)N]JntLWi&7N0B8#MvbamLn)p/NpvRiLFcB=#C[imL(MG8.x=G##"
    "([cP9Ha&:)g^6kXiR/s7_NB5B]k3/M7&D)+Ct4v6dDfw'Ixqw^dk)AFU[NJM<Sw],d,fw'BL@G.ZM`w'hYpF.ahSF.35Z-H[C9F%d'i9D9=Ww0i-_M:p%?<-)/8v$jeDs-L0SnLo5KnL"
    "uwSfLk?9C-5H=4%+9D:)wLF&#+P$<-/A,-M-T#oLCw?68K)8)=Njn,MEOx>-xq.>-0Y`=-xHQD-xfG<->fCH-?9xu-S/_1NAP5W-tm<WAwrPoL?[`=-%aYs-U6+gLF4$##(gG<-Z>RA-"
    ",GlDNXT.2N8r<JOVLgcP0jE?%7j7R*wXm-$(7Xv6,d$8@+5-v?Lf:<-.gG<-k`/,MOC4R-hxeBMDYVpLJ^@N%`twVfENx>-Pgd.%;^v9)1si*%1DW)#`S_pL0lrpL%VcS.u15##>kf(%"
    "`Fd9M%-DdF=t.>-YR`.Mo=a*Mi4JqLBqgKOjFF3NP%T,M;A,gLscSC8Q(g*%%Pc2VZ%B7N'pfC8u6c`O/c?<-ZgG<-T6T;-Zuj3MIbCH-N`G-MvChI*2rn&-T0iH-2;iH-gVCx$j=x9)"
    "pJ[YQ<=r%cpGwuQ2cq;-^N#<-^M;=-s;#-MV8'vL8E5O-t;#-M5RvA%umF:`#/98SKj&:)A#cY#KXqm8E:l%lSX6AlTbQ]lSD>R*Nkmxl9YZk+Kt2>me_l%lG8Uk+B;u;-a4D6&itRW&"
    "xDVM803/F.B;u;-$nl-M8Gp;-3O;=-xWO8&1[sr$&f[w'^er-$Gvk-$#Z8R34X<;$r.]R*+eiDN8(Pp7=5poSWH4=-)Js>MLwAN-&>s>M;IS;8OsklTbZ@-Me<.FNs;k?8065F%:#u;-"
    "s[4@&v-w;-/ml-M/gYOM2NH##b#T,MGh]<8HJ9/DfV><-KhYO-#l,t$Bsv9)+9wf;W$s;->Ki6&MTQGEKj&:)A#cY#IF:68M9hiUreN;7.VWh#RIi9;o`Lb%i/p-$uqBdk$br9Nf@?i&"
    "u4e$'7;Cdk3R.+8S:#F@/_Ts7$`W%X,LacWZMI_/,Rw;-a^5=&2VH;$qC[w'qGp-$vtWv6wO<`Wc0#3)Rc(AM_t%,(KbPDF%dp;-wlmF9B0?v$DTi`F+E5?I(A2pL)[vA%ISu;-?+A?&"
    "3i$<-Yll-ML'GX8Aa*#HSD>R*gP#<-VNLA&WYbYHKj&:)A#cY#9b:EN3NM.R$oMxLh07r7D^X]Y=9n,M#q5a&p=x>Rg#Os7>d9>ZSD>R*w'.:)*eiDN^v:T.t7>##I]sM-&gG<-#$>4%"
    ":ZR_&8kWV$@xw9)'U`2VoA^nL?HrM%:*`R*wLF&#fP#<-ZA,-MZgF?-m`dEMr@9C-lwj_OF*xU.vOc##T#]#%kkS_Jp<lwKYCEwT;U4xTJZG_&Ftn-$7?2R<*DkwTk,hwTt5K<-Bml-M"
    "3Vfc&2L'dt=t.>-H86&%6O#:)sWW&HC^k,8Crm--Tvx;-KY`=-D@5)%,C^>eAj'-8ZGNv6U%f+MdJv&:#(JP^>Xhl^C+L,Mf^_sLa@,gLR];':)o1R<Xvew'q<Rp7c85F%M:dEN6eSNO"
    "V3NJ%Ycw9)Mmi`FWrl;-O+A?&e$oiLKj&:)A#cY#9b:EN8QdE9;Xbi_vpt--^FD<-d<rAMf-l<%@n#:)f.kpB6Ac$MURF[;5M0X8?l-=N^evJ:OqYcaL/>R*3uH<-e;iH-F<#-MVnt)#"
    "pS9%MFLaUOIgZI8Ze7p&<=r%cs]Bq^QQU1Rqg/VOWT^`O(.w.8%6/F.p7;>dSD>R*E]QYd;'=<-[RA(%NB$:)P1]A,maA<-GhG<-<7T;-kU=4%)3,F%Bkq-Z&lt&#A<G##;S,<-Yg`=-"
    "qhj3Mgqa>N?xSfLJZx>-Y<#-MZZx>-iYx>-Hdx>-[<#-MZZx>-kYx>-Idx>-^<#-MYsQ+#oEqhLT?B?NPeDE-MhG<-$-XC&*a_e+V-F'MV'='MIj8O9f[<Ji+*N2iU9X'Ma07r7Vgs+j"
    "`J><-`<#-M9T#oL%NihLWEk'MC_E>Nr)G1<%ro(kl58R31[sr$BLE_&RCr-$SFr-$,<C:2B&cY#@#fN%$SFAur3Rc;9<P`kRnXh#e6n?nSKt'Mgo`ANE1PG-vvc1%Zr=:r1XRF.X0Js-"
    "Hd(*Mq[OZO/9S>-JW:@-&=#-MJUtG%ii':)S:s.rl5Uiqbxtc<vteG*mD6Jr`WdA#a+3v6LUgw0JB@['M(:`f&)JU)kJm+s$u8Gsd:<Z6LxKS..uX&#$/-F%CZJ:)5gIs9=[;=-xnP<-"
    "q&G?-,fG<-p7T;-S`/,M-=+)#?%mlLvbA+M^N&/NmP&+Mw$GCNp:$>#]uv(#$m8At-YSBi";

