// File: 'draw_reduce.spv' (6740 bytes)
// Exported using binary_to_compressed_c.cpp
static const char draw_reduce_compressed_data_base85[4840+1] =
    "7])#######<cR%>'/####vB8./Dc>#;K?D*IfNcMVEj$#2_e6/.f1$#nFwqLIVjN;e/W$H_>Pe3oCA['TxL$#4(gGM$@W$#b.xfLmcm)Mn6T=B.cj*%<tvV%/k7p&/3kM(4aG,*7&D)+"
    "8/`D+.*O2(Rfaw0j?c$0/8s9)%%?v$qn>L>^.LcD-/2eG7X$Z$im*:)tpvgFtv*7DlouhFqi1EH$3a]A3YHlE#87FHuOw#JT/orL1MwA-:xS,Mt9R2M1qluBO_oTUZ%g+Ml0M-MalL5/"
    "'^TSDBY5mN/xSfL)_$kE@E<:)$/f+MpC6##UXs-?.vIqCWYKtLPT@v$;RC#$NZ?gDrQ2]A@n6Z$t-GR*ed->Bq8uLFKV6$Sf>7I-alY@M4-DVCqmiTCnAm@Msdn*N5WY@MccY@Mk%Z@M"
    "`GDl-n_=R*=?`&#VK3L#bV###_MH[A#n.>B<eq6Mcq)$#7d,t$2fuhF_0m[AI&+sL,WnoD8FYpLO1oHF(BG/#_;4W%@Sl_/O08fG-MViF^(nI-W@NP&t9w#:*^rTCw_st:/qB&,Zdl2C"
    "#t%^A7Yma$(NrTC9l7FHculhLl_d##J=@Q/q&sXBk--[AsIMk+jVOV-BOA5B'4HZ$H`kr-/r[PBOU5s.0%xlB0IQv$q6HkOuX'.6-p76D'&9Z$A7Ib%3l`SABdC2C6FU#$$d)l4M6gx="
    "Fv*^G,t)kNK%^pC'bv[A#?pKF`N:@-'#DT.Z9'##w(B;-(=?%.jFW3NVZx>-q-b+.GX6?8x?Ok4K8w9)Nao;-A,TgL=MH##Dp(9.vN[mD5[HZ$IQx:HL>b>H[#0&8H7F2CK;cG-H8Lw-"
    ".q5tLDD(cH7Vda$;+2EH*HkjEU`Lk+$,f+M<6MDFIexPB5$;qL[XQ##1?2UMG<T=BM**[8U16Z$C+x9)4.VeGkN6:2*if]PqI^k=2[RrQm*Lsf_@eA-hw'w-=88vLww46D:mG<-$hG<-"
    "@a/,ME@=,8l;U#$,AK.-&K0`jBT%aF`(-:M##JfLsL&3C->MaH,Co-H(d,]k<0)dE8MG_A]<K_&EQY_&&>FcMjYE)F]Bm:29ph:28gU:27A^l8.A:m9UH3L#KYqr$J)P2(g$C2::AJb%"
    "@(T;..VWh#:kwu#tIX&#blZw'L'dA#D.9v-IDhk+w%f+MQopcN/@GGMBW%iLV)l?-;xS,M)Y1)NX5LP%KO):).A#W%J+hw'OCt9)k+)RN?J#F@,dlE[6:P&#P`sfLD$m-Mm<.FNd$(w-"
    "Tx*GM?FjJNIR()N>3%*N/G@*NZnk0M^NrM%FA,:)-W=p&Esjw'OCt9)AeL#$++m<-<TvD-8M#<-)5T;-I4m<-G4m<-V_G-MB6S>-KL.U.<;G##(M#<-L`/,M4QrhLCC:p7k2.m0E-[;%"
    "Nr@&,.7_>$+4$Z$%.Z;%<Sw],HOL,MN2oiL8(^fL?G6##SxefL^N&/N/Fl(Nw;,&#wnrEI]Okk4,<,F%qYOk4/^C_&*tj-$ufOk43[vV%Q4+^,D'5[$m,i.$2V)R<50v2;TT[I-B:#-M"
    "J2oiLN:.*N#ol-M)8m<-Qw$*.k3UhL;vPLNrG`hL6rJfLh]?T-G:#-Minl-M/4DhL.4pfLD0;.M-,m<-GqRU.>;G##>fG<-$5T;-/`/,MbQrhL#xSfLD0;.MZ+m<-ZE.FNG,F+NZA:@-"
    "SF#-M7b./MH2O+N&WP&#u8j+N.3CkL:?VhLE,fiLlVP&#'^J,NTnl-Mk?9C-4K?.%W'2p/BJ#F@5uT50>1Xh#^^*j1Vt6x't6U2`57m<-c(m<-@F1).B[I/N8(v[.9/5##+x_EN;TY0N"
    "v8m<-Oe6QN;jLx7p:BZ-(9GY>s@;9.T5>##pNjY?u'n;-,s:T.%####34m<-U0o3%9J*x'Gv-x'gCr/)A'&>GlQVv$x)0F%?5)d*rO$^O5ZUsLcq2?#6;bkOU>`w'ooUR<jJ1F%PFm9i"
    "NxFM_2[vV%b,hrenPs2DN30?N<9iHMmSQ##W#fV'b=p^fE^akOmx`Kc:)D_&:Nk-$;G[A,n`McsBh'^,wIF]uAi<#-^]U&5V@'DN(OtG%Un5R*Vo1ppJ+QDOLcB,N)K=jL^*elLGWOjL"
    "[Y^s7`Hp9;pNu9)R4]w'^<ZR*KD-F%**v9)(0,F%LCqE[Gsf:)ljkpBTDE6NsIH-Nf9+;.f;G##3u(:)1(G&#WFhM1WO-j1HrG/2*deA#g&bJ2J[):)[k)g2hN_w0O=;_AWC]w'BOg*%"
    "^tD,3]'aG3MI%d3J8T&vP+fQ-b2AB.%####aB]D4Z2#d3G8Uk+*Vs9;a_]w'fKx`4LX5s.V>:&5g^XA5,vE#$q+r]5J[):)fp9#6hxUA5G8Uk+*Vs9;fn]w'`+<Z6<<CG)`rQ>6<5j*%"
    "Fv+>#cldw'xAK<-).)iLrKJv7+/?v$a+3v6gTs;-5mTL&L-hJjpTNmLF[`=-Or:T.)CP##gM#<-Z+R2MW0'5#$;#s-D*+0Na1CkLH0;.Mga-2M<8`Q&`?OR<adoxc9sk;-o694MuF_1M"
    "iaE_OIHG0N0PqkL_(.A-(;#-Mu/BnL>(I=NaZc0NcshHO9<TnLr5KnLnS>OMeLH####T,MA&EE-xmDE-=2.A-t#Qt$).vc<cgZ&#$_3`/x6F_&0gSD==bh>$vjj3M&#sb&'MX_A=1U,M"
    "tSZI%5P8U)sLm-$uJk]>2o?<-dK?.%*vtJWIcbjL)S.2N`HVPMEYZ##(N#<-#6T;-8AY)%PS-F%2_WV$tIX&#wUtk+wLF&#Ph%<-=A,-McA:@-@V%3%7Qv9)tOm-$3`WGs02<PA6oWh#"
    "E;C;$7t.>-2mP<-pK[:M;et)#Nx%mB#qaG3T+A2Ct7$^OM)8qLb9R78;MtiCSD>R*.P3s7e6YJD<b9/DD5l;-KM#<--nI3%F5E:)xRO&#`M;=-QE5)%PS-F%X178%YR^&#r/G_&5@n-$"
    "Dmk-$S52F.6#SDFBB2)FZMI_/N1vw9T:uk+xRO&#IqdT-4)^,M9uLp.u%cY#V%,Rs.C/F%9HepgX#//ME'-D-udd.%0aW,Mg[?Q%K><U)9Ln-$>daYHw/t;-:M#<-K)H<-;XP5&i'lwK"
    "C-0F%K/V9VJA-F%[^o-$5>*x'G<`VR`+n--4U##(:O0x'&B'<-L)m<-=6T;-7YlS.t7>##,;aN&[($sIKj&:)j$<-vmkSs7p`c.U+[]`X/3kM(Ct4v6ogiw'Io[w't?iDNZu:T.^=G##"
    "u3D.MYj2B8vfuoJ:O.68xr:5K[uUk+owD<-_A,-MZ8Xg&X`w9)_[72L[SUA5_2p;-RgG<-Ya/,MsnWZNeVa6NcJN6N#k`=-Y)m<-a/GDNCm_=80^/,NL/+#H.VWh#b1F:)Y8d$'L0o-$"
    "qZl_/(a5`/X178%M.^&#kR>WJE6S>-q%u8&[8H_&?N1F.DDe`Oux,WSYiEuLT0;.MW@QA%g4x9)Zs,'?QDE6NEEp7N:1FGNV'buLEV]F-1F)>&rF-?@MI$N9;tZYQa9_w0$+Xv6dTRrQ"
    "Kj&:)/I<;$p(D_&cE,X8=t.>-rY.U.u15##7je+%LDUk+(caw'Gvk-$%ApoSOw5F%YHWw9o4aw'amo-$Rlu;-8l./MdZ8/N3pMxL*1[mL5%co7MPX]YL/>R*IB:Gscp##Z9+q,MF+m<-"
    "%vj3MrO&+MuW]F-)%T,MAWvD-OxR/MOR5W-R9akFIv:3DKH`.M/[?T-3B;=-p/GDNVC;=--nP<-j`/,MW4+)#`ti;-1*m<-L`/,Mk6S>-KR'DM:UN4982?v$+H28]q(;2LJKQS]K>-g)"
    "4_H,M=phq7ROSSSYA<F%:'UR3TkWd+r3kB-Gml-MZ$G<%(caw'3e'x9eP#<-^FGP&u*>&v?3MM%?\?]&dKH`.M*73U-inu5&)d6F.GoGF@bA@RWc1<v6lNRq$2g'<-?S`.ME]9=#L7cwL"
    "4@i*8>N-/VS-6F%cTml^:8JP^;?wct4s+$M?[`=-1O#<-w%jE-%/#P&4oI_&.,q-$&(<:;u(&)tkc4REqa4F%$ws&H=^]C%EWv&$T0iH-4PS<:Ye>GaSD>R*mR.F%&m(KN7Mu$MT1CkL"
    "[H[r7>xu(b=l^f`G8Uk+DC%<-PTG-M/(-A%MMH:`Q$s%cKj&:)6NR_&<AEMhHJaihIS&/iSD>R*C]AJi9YZk+@f]fiYP@MhG8Uk+*D$<-=JdE&gt72LWCRW&iWGL803/F.B;u;-oml-M"
    "[;4O%7dGb%6`]W/58ZX$#X<3)=t.>-$M=4%b21F%`))dt,mdEMxw>U*Nsv&$mlBK-7@t;M(mBK-5Co_'aP':)0]$<-'qiu$,AV>nU73/82]+?.B4%&MjBnR8HiIP^Kj&:)_mffV_v+,W"
    "-X<<-lsvh-v(7@%pNvwLF[`=-DAW/%t4M2rAt.>-4TG-MRfK=#_GL_&*N'<-:;#P&/LoreLHKVe*[7p&3Xn;-+^(*%VgH:)9sK<-ZB,-M03pk&5W.dk:vP5MVnt)#)Ym&MbQ>WOCY[&M"
    "m@9@%N%t2;8S_M#eq0hLTq*'M:*xU.f;G##waCq77pm-d$SFAuonUf:7JniLPhk-$%K.q^cPiXOqmY18&IL]l)-d&6[v^(Ma2Z@NLn?Q%emcw's=jQjiH0,N<)l;-&0;.M8RO;.$25##"
    "lk?xKk3i--U41Al(chuml0*;n2CIVn7LernK,>R*_*J<-'nl-MlNC9Mf0iH-,0;.M57S>-7RtJ-)nl-MFC;=-`M;=-BGx/MB@Z=M)6pk&)rl--d^XlpJg#2qpop;-:M#<-f7T;-WrbP8"
    "4Q&:)p&h$'O[g:),TC_&h-s-$SG;?[T_d##BgG<-g0h%%jK4F%NX+0rwi]=u]vlx4)SUV$>YVhf*####";

