// File: 'draw_reduce.spv' (6796 bytes)
// Exported using binary_to_compressed_c.cpp
static const char draw_reduce_compressed_data_base85[4880+1] =
    "7])#######u]F%P'/####vB8./Dc>#;K?D*KlNcMVEj$#2_e6/.f1$#nFwqLIVjN;e/W$H_>Pe3oCA['TxL$#4(gGM$@W$#b.xfLoo)*Mn6T=B.cj*%<tvV%/k7p&/3kM(4aG,*7&D)+"
    "8/`D+.*O2(Rfaw0j?c$0/8s9)%%?v$qn>L>^.LcD-/2eG7X$Z$im*:)tpvgFtv*7DlouhFqi1EH$3a]A3YHlE#87FHuOw#JT/orL1MwA-:xS,Mt9R2M1qluBO_oTUZ%g+Ml0M-MalL5/"
    "'^TSDBY5mN/xSfL)_$kE@E<:)$/f+MpC6##UXs-?.vIqCWYKtLPT@v$;RC#$NZ?gDrQ2]A@n6Z$t-GR*ed->Bq8uLFKV6$Sf>7I-alY@M4-DVCqmiTCnAm@Msdn*N5WY@MccY@Mk%Z@M"
    "`GDl-n_=R*=?`&#VK3L#bV###_MH[A#n.>B<eq6Mcq)$#7d,t$2fuhF_0m[AI&+sL,WnoD8FYpLO1oHF(BG/#_;4W%@Sl_/O08fG-MViF^(nI-W@NP&t9w#:*^rTCw_st:/qB&,Zdl2C"
    "#t%^A7Yma$(NrTC9l7FHculhLl_d##J=@Q/q&sXBk--[AsIMk+jVOV-BOA5B'4HZ$H`kr-/r[PBOU5s.0%xlB0IQv$q6HkOuX'.6-p76D'&9Z$A7Ib%3l`SABdC2C6FU#$$d)l4M6gx="
    "Fv*^G,t)kNK%^pC'bv[A#?pKF`N:@-'#DT.Z9'##w(B;-(=?%.jFW3NVZx>-q-b+.GX6?8x?Ok4K8w9)Nao;-A,TgL=MH##Dp(9.vN[mD5[HZ$IQx:HL>b>H[#0&8H7F2CK;cG-H8Lw-"
    ".q5tLDD(cH7Vda$;+2EH*HkjEU`Lk+$,f+M<6MDFIexPB5$;qL[XQ##1?2UMG<T=BM**[8U16Z$C+x9)4.VeGkN6:2*if]PqI^k=2[RrQm*Lsf_@eA-hw'w-=88vLww46D:mG<-%hG<-"
    "@a/,MFFF,8l;U#$-DK.-(^g@kBT%aF`(-:M##JfLsL&3C->MaH,Co-H*vc=l<0)dE8MG_A_BK_&EQY_&&>FcMjYE)F]Bm:2;vh:2:mU:27A^l8.A:m9UH3L#KYqr$J)P2(g$C2::AJb%"
    "@(T;..VWh#:kwu#tIX&#blZw'L'dA#D.9v-IDhk+w%f+MQopcN/@GGMBW%iLV)l?-;xS,M)Y1)NX5LP%KO):).A#W%J+hw'OCt9)k+)RN?J#F@,dlE[6:P&#P`sfLD$m-Mm<.FNd$(w-"
    "Tx*GM?FjJNIR()N>3%*N/G@*NZnk0M^NrM%FA,:)-W=p&Esjw'OCt9)AeL#$++m<-<TvD-8M#<-)5T;-I4m<-G4m<-V_G-MB6S>-KL.U.<;G##(M#<-L`/,M4QrhLCC:p7k2.m0E-[;%"
    "Nr@&,.7_>$+4$Z$%.Z;%<Sw],HOL,MN2oiL8(^fL?G6##SxefL^N&/N/Fl(Nw;,&#wnrEI]Okk4,<,F%qYOk4/^C_&*tj-$ufOk43[vV%Q4+^,D'5[$m,i.$2V)R<50v2;TT[I-B:#-M"
    "J2oiLN:.*N#ol-M)8m<-Qw$*.k3UhL;vPLNrG`hL6rJfLh]?T-G:#-Minl-M/4DhL.4pfLD0;.M-,m<-GqRU.>;G##>fG<-$5T;-/`/,MbQrhL#xSfLD0;.MZ+m<-ZE.FNG,F+NZA:@-"
    "SF#-M7b./MH2O+N&WP&#u8j+N.3CkL:?VhLE,fiLlVP&#'^J,NTnl-Mk?9C-4K?.%W'2p/BJ#F@5uT50>1Xh#^^*j1Vt6x't6U2`57m<-c(m<-@F1).B[I/N8(v[.9/5##+x_EN;TY0N"
    "v8m<-Oe6QN;jLx7p:BZ-(9GY>s@;9.T5>##pNjY?u'n;-,s:T.%####34m<-U0o3%9J*x'Gv-x'gCr/)A'&>GlQVv$x)0F%?5)d*rO$^O5ZUsLcq2?#6;bkOU>`w'ooUR<kM1F%PFm9i"
    "O+ci_2[vV%d>HSfnPs2DP?B?N<9iHMmSQ##Y#fV'b=p^fGdakOmx`Kc:)D_&:Nk-$;G[A,n`McsBh'^,wIF]uAi<#-^]U&5V@'DN(OtG%Un5R*Vo1ppJ+QDOLcB,N)K=jL^*elLGWOjL"
    "[Y^s7`Hp9;pNu9)R4]w'^<ZR*KD-F%**v9)(0,F%H#l-$%Ni*%3SJ:)ljkpBTDE6NsIH-Nf9+;.f;G##3u(:)1(G&#WFhM1WO-j1]XH/2*deA#g&bJ2J[):)[k)g2hN_w0O=;_AWC]w'"
    "BOg*%^tD,3]'aG3MI%d3J8T&v<^YO-b2AB.%####aB]D4Z2#d3G8Uk+*Vs9;a_]w'fKx`4LX5s.V>:&5g^XA5,vE#$q+r]5J[):)fp9#6hxUA5G8Uk+*Vs9;fn]w'`+<Z6<<CG)`rQ>6"
    "<5j*%Fv+>#cldw'xAK<-).)iLrKJv7+/?v$a+3v6gTs;-5mTL&L-hJjpTNmLF[`=-Or:T.)CP##gM#<-Z+R2MW0'5#$;#s-D*+0Na1CkLH0;.Mga-2M<8`Q&`?OR<adoxc9sk;-o694M"
    "uF_1MiaE_OIHG0N0PqkL_(.A-(;#-Mu/BnL>(I=NaZc0NcshHO9<TnLr5KnLnS>OMeLH####T,MA&EE-xmDE-=2.A-t#Qt$).vc<cgZ&#$_3`/x6F_&0gSD==bh>$vjj3M&#sb&'MX_A"
    "=1U,MtSZI%5P8U)sLm-$uJk]>2o?<-dK?.%*vtJWIcbjL)S.2N`HVPMEYZ##(N#<-#6T;-8AY)%PS-F%2_WV$tIX&#wUtk+kiG<-=A,-McA:@-@V%3%7Qv9)tOm-$3`WGs02<PA6oWh#"
    "E;C;$7t.>-2mP<-pK[:M;et)#Nx%mB#qaG3T+A2Ct7$^OM)8qLb9R78;MtiCSD>R*.P3s7e6YJD<b9/DD5l;-KM#<--nI3%F5E:)xRO&#`M;=-QE5)%PS-F%X178%YR^&#r/G_&5@n-$"
    "Dmk-$S52F.6#SDFBB2)FZMI_/N1vw9T:uk+xRO&#IqdT-4)^,M9uLp.u%cY#V%,Rs.C/F%>iFwT'OG_/+W_PBS7Hp7S.ew'x5'<-KGD=-Ga/,MQ<6&8M')d*?We]GLm*#H=5:<-i.iH-"
    "CN#<-K86L-JM#<-[6T;-C_G-MN9iPOJ6S>-5Nm<-]aCq7]0B;II,F>H3W,g)plVGsIj9SI7)t,MZKCsL>C;=-xR&GM>nt)#Ho4wL,hDxL3QR*N?=*mLb,m<-kRCq7E4]R3^R:&lZQ9D3"
    "DIt-$W0X&Zbp;B8N0T&ZNdhsLqQw78U$VPKL/>R*dNJ<-gll-M^v-tLsBfr8F1RMLSIniLG8Uk+oKjR*eR^R*7v;_og*OJMZqjfMG,cR*7`TW&RDetLL'crLw1K;-bM;=-YmP<-Za/,M"
    "csF?-*:(w-d:4gLv5$##u,@B&kBOJMb@;<-j;#-MCHkGNGVlOOFbBH%f1x9)'Ah-6<ww;-ull-M3@QA%7%N_SEON_SNgt-Zi:x9)G<0g)<'=<-WGZ&%P0RW]`1tuLbSF0MK[X)#;,&vL"
    "BhRU.a;G##:fG<-Ht*$%wrWVR,M8)tfmNoR%8K,M>t.>-)*m<-U`/,M(+v8N>P#<-Y'kB-o)m<--kF58QF88SS-6F%v=Nkb.7#:)s5i*%2ro&$#$axLM0;.MHFj*M#>FG8hMUk+.0UYZ"
    "*^7F%W%._S+BQcsKDUk+*usuZ$>R9ixRO&#sx+G-0Ds'%mBG_/d9YV[nYWVRWhk_/6amr[e1nY6[Bv92tvs+;r?28]J4X>-$'QV[K]m--=J;-m[+48]7r%?n(@,gL4G-TOmEE6NK*u;N"
    "_jsn82M._Sl/Rd+i$m8NHR#<-:d_@-?<+8&t*LP^SD>R*d:v;-7TG-MF_Aw7hc45T9/C<-_FGP&8u$<-bNJG&gt72L1AQ&m*:%b8_5/F.g>lJ)tRhiUkkl,M_ED9NUUuG-715@M4RX)#"
    "uoT58Y^),WOw5F%B/C;$XRaw'>iHK*uZi9NP%T,M;A,gL8s+$M+mx#M5.xR&EK`R*2P2F%wHQwBXbIK*4#5$M7/G$M4Yh<NqcYs-N1=GM*Ks*McdWo87V4KNJJ$.8SBqwKcx<xKS^x;-"
    "Rml-M'0BnLPoZ.8Yuu(bTQ*j1G8Uk+/]$<-PTG-MWRw7875V`bSD>R*Tjx;-]%g?MS(.]MC5$###X)>Mr.hK-IRhK-JRhK-lml-M,;hK-NXB<M,/hK-nml-MWRw782kScjSxk,ME;`Q&"
    "o[YW&h,k884'5DkSD>R*+N'<-7S,<-@F#t&fFd;-'Buw$#Z8R3v'Q,Mfv->%=xMb%%Y=F%;[a=-Tf/%)Jjo_]Zrr_]GTJ_]ZfM_]f)&Ka[#S/Mfa[I-V47:Mw;T8%c`m2D`Mw>%PH$:)"
    "+&[pK/mx#MP<.FN_h%:Nreeb8r$acW9/i]Y^Y@^$)(#:)]HM50W$s;-%Li6&4t]`XKj&:)A#cY#IF:68'8grerq;<-R=9C-O*m<-B7T;-WX@+%b*6WSK't>Ne)RU&Nnf$'6wf32cn/08"
    "cAgreWC/F.9tsr$0nJ_&NJR.?Ztm2;b*K08-2e>Q8k+/(VM[ihCj=R*3X<;$bF_1M8D;:%R)<F%E)G>#mvJk&n^Nb.WIhxl0TB<-f*H<-GRB%%]$4F%rwv;-p<#-McR[^&kA%:)s=jQj"
    "iH0,N<)l;-(0;.M8RO;.$25##lk?xKk3i--WFhxl*uHVnnBarn4U*8o9_ESofBarnwo>j90R]oolaASoQdo;-tHlDN3_d)Me>6)M>6S>-7RtJ-'UG-MuVZ)MSPW6Nx78BN1dm)M.@Z=M"
    "b,RU&#/=R*fp9MqL#Ziq`xmY6oq*d*l;q.r4aG,*&%d&Q6C;=-rnP<-(ZV^'vJdw'6B/?nT_d##BgG<-K-f+%TO8Jr'Gagrwi]=u]vlx4)SUV$k37Zh$$###";

