// File: 'pathtag_scan_small.spv' (7760 bytes)
// Exported using binary_to_compressed_c.cpp
static const char pathtag_scan_small_compressed_data_base85[5390+1] =
    "7])#######<V`c<'/###$vB8./Dc>#;K?D*B.-##06'N(blZw'T1NP&(.p=Y)37n9=4in1H)Dq1?(VkLcaKM'Z#p*%SDYm'7(VV$ES2-*<Rd%F4<7rL>_`=-+S,<-*5T;-/5T;-25T;-"
    "75T;-85T;-;5T;-<5T;-=5T;-C5v5M/$S/MK:3NM]@,gL,WO?/P*;LFAH[rLK:#gLOlXU%/%vLFe*?[Ap2JuBw`poDvQDTC7d'oDo#a]A/f@jFfnXw0fSX8&2cWh#/P(:).giTC(:S-7"
    "x4+gL-0M-MbuhP//TKKF-PN_IOGlR*(N_$':.DEHw/]6D?$[v$X.f+MTq6AO4tCrC:$;qL]fC)Nj.gfLJ`:GHLE3kNnLYGMVX1)Nhh7u-b_0HMjYq:Ba8uLFL`Q?S.bZ##tJ'tQk&47/"
    "*)%bHB4J9U=OwA-'(=^-q:&:)/p76DFA]$KCA:b8cZ?D*Q_-?.d07r7IC>R*xd7.Magi/)x.,?./LYGM]Y=W%F####w(B;->@Rm/$<p,GvlpKFS;#-MJ#+fMe:.^Mcq)$#$u@T%*mnmD"
    "p,KkEngjjE&%F(Iw]CEHug)]AD$JT:AROGH2735&D`l_/P4Lh,3_>_/lJSY,rk6<I-Q=7D@+8/G#,1T&#Iw#:)^rTC_/>G-iNp$.#-wiLn7I'&:/>*eGd#&J^06s.K6cmBwswmD5km/O"
    "#/ex-$KNjLBfipLOXQ##%QWjL3:43NPotjL2.]QMURQ##6,l58Z$d*7Zp7Z$bgakF:KC2C%YF&#QJA/;M/]J;K84'G4ieFHve3cHRVh--R&[o@H^VDF<SM=-rg_@-^FI*.0B`QN*Pc)%"
    "Uxe34[iw9)^;S,MBD;=-(mhq7oDat(F0r>$=ow9)P;MqLtt:T./Mc##RN#<-ve66NAXY:CQ#..H^,Lb%vYn6DpBniU:hpfD9_$Z$*w9>ZYG=Z$-.ww0#Tr=B&AQF73YMb%'j].#1x&2h"
    ":hpfD'4HZ$e_wRn8[Q?$-D,##p0USDePPs-tD=[PvdJk&;t<;$tIX&#@*vE7.*k-$j>Me?2`Nh#Adk-$fn'm9(vE#$%f'^#hgv92#w+F%@ak-$>bh>$++m<-Q:m<-/.m<-PRG-MQ_YgL"
    ")KvD-MDIv8M8T;.$Y;F7vxe+M9WvD-CAQ5MK8xiLKPD6MlVG-M-AZ=M;v@Y-#s9I$C^J:)ii':)tLJ_/G)###<@*F7JwC#$>68p&Jf9R3WL:R3=t<;$#95RaVpJF.e#0^OV>.FNH(TZP"
    "@-m<-t>nY%vxe+MiM-+9x'd:;73?:;.V);;L=tY-IA@w^;kwu#++m<-ORG-M2f7iL-_YgL>>b+NKDk+NI8X+NLJt+Na;x/MnP',NGvRiL7E`hL_B,gLB2oiLw1K;-A(m<-+=cH&j;4.-"
    "9cA:)Ff[w'*NC_&#_j-$%ej-$px4kO&N+:)V3Mk+i5g9;I)###VWj-$j0,x'3PA:)g@vu#ok)M-]%.A-:xS,Mcr-A-/fG<-8`/,MuF_1M6qU)N#E5&#l?H*NBS]cO;vRiL(x(hLea./M"
    "`rugL:O.U.G;G##lUwA-vosRN:3%*Na-'CO]W[*Ninl-MU,m<-_9iH-<3@'8,()d*:CG&#vJH&,SjK,*dZv92p9&RN?P[w'xZj-$hSARN?sgJ)V<,REb2iKEIs9W.>;G##Q`]F-3xS,M"
    "vj@iL#xSfLD0;.MZ+m<-_E.FNS7D]PLJt+NkLwA-JrG<-^WC9MMP',N&WP&#$WA,NN3CkL=QrhLJJ=jLlVP&#,&#-NTnl-Mk?9C-Y@;=-K9;.M[OQ-NRvL#8.D*j1>1Xh#c5^G3Vt6x'"
    "x7lp'57m<-h(m<-3.GDNmTNmL,FPGMxMH##?(hhOsB^nL1.gfLOM:@-Z?*RN'a5oL.4pfL/7m<-+)m<-Mr+DN.5voL=x=`N1G;pL+xSfL/7m<-:WDu$BkTJD2[vV%1TRDFc]bDNZ3urL"
    "2h6]O^E:sL6'2hL?BS>-Q)m<-`GPS.8/5###Nk3.39dtL.iG<-_/o3%kUB-mRW&F.MS_:;_AH_&TA,##GR;;$H`H_&i_ucMv6QwLXF6##U.xfLkPG&#OI(xLD*[Q8LdtxY4I?v$TbZca"
    "qS&'-A:e=N>KI*NiW(pPjQ>WO2WP&#kEqhLW`AN-nx=G-_Pc%Mw.K;-DYlS.t15##EM#<-wO#<-Iiu8.]),##mT6s.:%Xh#G&1I$v,YpBOI)EOQ+q,N.jkjL^*elLLv'kLax5t7A>pV."
    "dF/s7[aeM1N3I21ev*j1t,8)=jcQ9iU%E_&Dmk-$CZJ:)W1a$'-gi*%K9D6NtC_kLbSF0MK[X)#+p/kLKePhL&I(DN[o).NXPqkLsK9C-^mDE-7X;=-mAv5M=pDE-e@;=-a`/,MO8v5M"
    "Gc6lL=&EE-amDE-QU9C-cmDE-8X;=-f)&'.XFB`Nl,elL`tQlLHH`.Mr@9C-m/EE-fmDE-VU9C-hmDE-9X;=-wAv5Mn)E'8S9jV7hN_w0d=@F%0N.;6CQ&:)%t5s7lYM88]&iS8-)b>$"
    "%1,p8J[):)puI59hN_w0ZLpQal*^w'BOg*%o=R;84qbP9<5j*%Fv+>#cldw'-_E<-3.)iL'<l<85-?v$k0C2:rqm;-JTN;&bTo&67I=)#,v8kL>LO3NOFw=N[cl0NNB^nLs)KS%u-F_&"
    "j1m-$Q>l-$v;g_/v0F_&k4m-$o@m-$Wu9)=K,>R*uk.F%HP8_ALms`=uIb&#Hw]w'u-F_&>Cg*%>3+<-$UvD-C=kB-MF7I-l=kB-(gG<-t5T;-K%kB-wM#<-.a/,MHnCH-*mP<-V5T;-"
    "x5T;-0_ZL-l1kB-7GlDNHA2pL+;)pL:Yn>8CL)s@j?]k+PXE8AlFnY6+0cSABtWk+Rk&pASD>R*QaTd+1fipL>[`=-R`uG-4gG<-&6T;-Q`uG-AM;=-ZMk3.dr6qL6C;=-rZYO-ISG-M"
    "uZqS-9mP<-'-CK-LSG-MumwFNt9?LOiZ]C%D#w9)G6qfD;Yb>$MRTGE6oWh#o]ncEbq5)FGWMDF`-m`FA9mcE6t1)Flr5.6eL</HJ5w9)Mmi`FcB*:)>;C<-649s$Q_[:;&a]SNM>w9)"
    "SMbYHZeQk4;Kd:;6W9:;Bw2WJ[HH&8$6^VI4q<<-X;#-MFXX)#3]7R33qKx96?xw9RIDx97Bxw9<^Fx9NgG_&n#MK*KjqsLLnl-MQxP5MBohq7pucG*M%rlKnr3WfUh$R8F5RMLZR72L"
    ".VWh#2H5Wf=pIiLWuoNO]%#OOlSJ_8rcjfM+Ht;-TN#<-.54R-MM#<-X6T;-9@m<-:Nm<-BBm<-SfG<-aNm<-qZ.U..CP##ZgG<-Q6T;-N6T;-:YlS.t7>##f#T,MnU/+MiQwtLYc<uL"
    "W+K7NYjG<->p-A-m)m<-<7T;-o=RA-=QF0MNJ=jL?+>DN$+c`:QT:_A],fw'?(')tkc4REu#YF%?7?_8^L[2rYoNuL[tQlLAQrhL[uWuL?8xiL]<*mLJK#8N3oAK%fo`w'L0o-$SlC<-"
    "dmP<-[a/,M[6LS-emP<-ha/,M.Dj*MS1`PO<:'vLfC9vL@nl-Mpc:ENM(TVOOveQ-L*m<-i8Pw$PS-F%Mtb2iHkW>N5P5W-?+F:)Kef$'gM^G3A-n;%^/,F%Clq-$%K2q96vP5M*OEmL"
    "[_e&M]K5WOEhF?-J%kB->@;=-pJDiL4Ts:Q?T?D*Ls_lg#uWv6b<VuPACg*%AWS=#uYm-dRqm-d/G].dm.aw'01qJaxe:a8Raa-?jcH_&)Zi*%xqxE@aP':)ka75TKSF,M7[X)#(f)'M"
    "X1CkLAIuG-:S`.Mo=a*MP&6wLqn#wL_@RA-<l./M*nDB%Yd$:),-M&ZR'='M?[`=-d+4,%^@R&ZOH`.M]Wg?N'&T,MXW]F-t:WFM,uCq'9#u;-LVP5&&#=GjknrxcB=r;-aB;=-f$ju$"
    "LHH:)>FCq0=t.>-^M;=-cB;=-]b/,MDB8C%`^cw'LO)3;aVrXOHv.>-pTG-M>X)>MuIdH.&&###gmnDNe/gfLDu.;%k3d>$SD>R*gnQw9l<)Z$bA^G3S]Uk+mEDv$:dIk=DTAp&;Scd$"
    "5Js9)lcS,MZ3urLHs)J%>@Lk+>M[w'xwLwK=2D_&7Ps9)?.s>n0XPgLI:S;%0[sr$CgF?-9@;=-s&]/M?RGgLaKtG%1dC_&D`pDN8(Pp731ixl;I3=-IP?.%u_nY6#rm;-RCo_'aP':)"
    "'NolT`:G,Mi@9@%S7_>nCOx;%lD%:)gM^G39N(_]LI3F%3e'x9]6&<-?ZLq7;;hiUSIniL.VWh#]P5-vo`Lb%i/p-$5I2j1ZJ:&5-Ln;-'M#<-UoWo87l),Wt)w92K@IGWSD>R*dD2s7"
    "Oi-)X$4acW&7vV%bmAm8T-ADXEOg*%HK+<-2B,-MBT+[&>9ppB:vP5M@.NM-3Z`=-%JQD-t8NM-(M#<-IJDiL.53>5GKo;-*nP<-0LFV.e5>##8<#-M4jG9%9Ai>[3B8#MG^.iL[H[r7"
    "V<mr[t(h-6E?R,Mtnhq7eD28]HOL,M5>8F-XB)>&Edwk+to;,s3H&M^4pio]:'=<-Ul./M_[?Q%nJ%:),#dd=gJH)MdK3o84HASo6up,MF+m<-fvj3MFiT=#5Y]F-)%T,MKHJW*u&jd="
    "%]OZOO)gK%u`%:)dvNp^/DF09q@Uk+prvdOj%<*M;E^4MZcB=#OisZO4v.>--UG-M*5t;MWn*G%(r@?7:klgL0Q#9%aQsP'SD>R*fZ8m'0RH,M%QS$954O2(:68p&G8Uk+#.w;-mrs;&"
    "IVA?783DhLO^.iLQ%Os7URK/)SD>R*UAoKs7?VhL5mG9%UNB?7Mjsn8qJv92'1Ov6U%f+M#:R78tRp9r%V9dO>P=O82,3Gs)DK,M3IS;8pgMcs1u>-Me<.FNPn9H8f55F%5kw;-<>bK&"
    "EC%<-7nl-MpVw>%i#dw'3e'x9HO%<-QrAwPEXuD%vvHdkjqRn958FM_K,>R*&lt&#e5>##A*^,Mk[?Q%rnJFnjUZd435P$MF[`=-'eCx$5Y2F%r(JDtU%f+MJAc$M>`q<Nv?up7Q-J`t"
    "F%;_A6uH<-LY7?8W?+AuSD>R*OjF<--g4@&mBkp':(u48G4/F.:Ao&#$&>uue.kpBY2r]$/8s9)P4x<(&Ar--_t_E[&gBR*:?jDN0R#<-LqdT-Iai=-37T;-Q-hP'I?H:)^:D<-MB,-M"
    "H9gN-I8gN-(<#-MVnt)#r`K%MHXsUOWa9HN]'n.8_1e>Q8k+/(GqnxcCj=R*?Ex%cACg*%p]I+M>V>l&k&:-mJPdG*u+scs=WZ`*2da-?K=9U)?8D_&<m,F%CZJ:)H.t9)W*6;)I1t9)"
    "Tkg:),TC_&J4t9)H)/K<Uem##RgG<-K@;=-ZbgoLj*Yo0@&###x+,##]),##?Jk^(;<&##";

