// File: 'pathtag_scan1.spv' (6052 bytes)
// Exported using binary_to_compressed_c.cpp
static const char pathtag_scan1_compressed_data_base85[4170+1] =
    "7])#######4$dbW'/####vB8./Dc>#;K?D*-gMcMVEj$#2_e6/.f1$#fl-qLIVjN;e/W$H_>Pe3oCA['TxL$#4(gGMMw(hL-:#gLO_e&Mn6T=B.cj*%;kZ;%-XV8&+eR5'0<0j(1EK/)"
    "4aG,*5jcG*6s(d*.*O2(cq:R3a1WU2#w+F%%%?v$7X$Z$6oWh#=J/>B#t[mDJjG<-J9;.M>Rp=B.QOVCK1o:.0Mc##PBD^#U='DN6$DrC,PiEHLJL@->w.>-=?FV.F.EmE'P9C-9_`=-"
    "D-;.Mhh7u-b_0HM(Ar:Ba8uLFkn#[A9ieFH&uR/Gqm*nDp<M=B[5XSMx_:)NGC$##$ExUC(v&$.ce9HM:?DVCqmiTCadsjEQFSXTdRGgLhOU]O*4i*NP,fnT.jRQ-v'=^-q:&:)/p76D"
    "1/*U`?&YE8x4+gL@0Iq77M>R*_ck-MKcrN*g(OpBh07r7e?-Z$Pnhq7]eb&#U.xfL)klgL.TISDrrcdGCpnrL:C;=-S0MeMVZrt--@)78`2(<-q(vhF^0m[A6%&jFqfpoDud[mDI4qHF"
    "(BG/#2`($#^sF?-qPerRkv'w-usMFNYV,jF02DeGYi>iOBx2$#?0h?.)G*_I;;J&#pio;%@]Uw0prJgL/NI2.T]'TMT&]iL80wgFvS>LF?fiF.X^V#$50Mk+*um-$OMuu#x(-F%7-l_&"
    "E2-F%6$Y_&5vES7OREN2RXQ##BIMmL/Kp8%5qF_&s'gS8&EKtq3:u&#,;G##tIVX-j$O-Q+@HZ$pR#29E,k>H$3a]AtpeHd-rF&#@0[G<1xR5B,1Y_&/_F_&'5l/#GvE>HF&O>HApG<-"
    "^gG<-26T;-%CsM-&6)t-oYB%M4AlFH9*Qt$nw^4f$Z/'-B9_*#nY&gL4o18.Tgf;-3O;=-9RG-M24pfL:O;=-4L;=->X;=-5L;=-P-m-M55RA->@;=-m8WFM0@,gL>dn*NEcsj$w='DN"
    "+u&nLHE;=-PJ:@-#M#<-N`/,MlwQ2MQopcNVC?##CA)d*to=s%2cWh#f;X.-73?:;$8);;L=tY-*(A_8[*iw'=W3kb?u(:)vxX8&:Pgw'AB,.-vxe+MAQrhLW`AN-5M#<-)5T;-J4m<-"
    "D4m<-W_G-Mc6S>-H4m<-V?S>-Cr:T.<;G##(M#<-L`/,MSS559qM&:)JVnA,+)6X1JPUV$bnx],'@n;-cnJ;/)/5##]XbgLw-gfLY*elLoF6##QlRfL@nl-MORGgLV5l?-L9;.MiSF0M"
    "99eAO7SQINU-r)NTnl-MV+m<-XJLw-hq0hL>eZ=M*8V'#N:4R-Y^./MkqIiL9w(hLelk0MN2oiL8qugL.4pfLD0;.M1,m<-QE.FN@W[*NnpJ%#j9_hL,@,gL%R()N#BVhL#xSfLD0;.M"
    "Z+m<-WE.FNLcY[PEv3+NU$iH-QF#-MWmk0MF&=+N&WP&#s,W+NN3CkL6'2hLCvRiLlVP&#%Q8,NTnl-Mk?9C-R@;=-K9;.MT%h,N48`Q&UUt9)ZQQd+RIH-NE8m<-[(m<-RDkGNab6lL"
    "1w?AOf*elL*4pfL^W&%#>CDmLpVP&#HbrmL.iG<-1H^s$Y.v;-RKx>-RJRA-&Ywm/,&###G;G##6;#-M#F5O-VSCq7SMtiC3@$Z$`Nv92lZ*/-mQ[.-[M*#Q6hvV%)-<8SEu<#-AGFM_"
    "&`bxu+*[#$0pJ_],IWV$J<7I-RRG-M8j@iLnIs*MDrIiLwnS+M?vRiL04x(#(^k_/Hl[w'?lsY-V8u`4t%q;-M(H<-)VwA-DM#<-]HvD-FM#<-A5T;--1p0%pNu9)L`D_&[6ZR*I>-F%"
    "**v9)(0,F%LI-F[wLF&#]<M50.]8I$Hr62Lq,jP0t[Vk+4X<;$/+]w'BOg*%*X__AT)W_AYD&`AV/W_A7if:)W2W_AK=`_A^nt9)K,l-$O=;_AArG/2JI.`AY8W_AJI[:;[>W_A8lf:)"
    "]AW_A:*YRaZ4E_&q[Vk+VbdJ2Kj&:)d9A)4`B]D4Pew`4,vE#$oo:&5J[):)o*]A5hN_w0O=;_A`[]w'OU.`AdVW_ATh[:;f]W_A:rf:)g`W_AK=`_AmEu9)ZYl-$[]l-$*Vs9;eRE_&"
    "[imY60Xn;-v8ZpLL4$YuSue+Mn+k?%qW:U)_fl-$eebP9#hZ#$m],F%q99`&r<9`&o'k_&(0,F%*3BWAis&nL4I=)##?<jL1aL=8uA3x'QJRx'L`D_&nUxx'&i/x'xRK-ZptE_&j8).?"
    "3Q,F%B)(v#LR.F%ol.Dtn:F2:oN?/;i6$j:Z[P_&>?Hk4,n^w'NEa?n%q+w7n(ew'CDD_&`7/s7qE4/M9W0j(h56v62]gw'?(')tkc4REu#YF%qFl--xLVw0mQvf;[SUA5:NO2(qg;,<"
    "8/`D+]u2v6[/]G<qS&'-sS#oLnZWmLR/wU&#@b$'crl-$j_g-m$Cb$'o@m-$/G3GsaUq`=Y$[D=%T4&>?E&:)Ja<kOC%`_A]N)`APs,pAZqjfMu'n;-XSo'.[4+gLWi&7N5P5W-;'JdX"
    "Wo/7N_%1kLX'<$#KjF?-YgG<--6T;-D5T;-[a/,M*OEmLE.AqLcIYOOEhF?-4Ruw$p6vk+&lt&#d?G##3S,<-ca/,MG[X)#Rg01N1P5W-`9oQaR)<F%=@VA>FR7#?+sk]>JUr;-xM#<-"
    "arJ0%)LF_&)Zi*%Z1)mLS$S/M9WvD-wK^s$fCWv6^tYxOQtlS/N#sEIAVtk+pVm+s_6+s@0JH;@lr5.6Cu5.-K<CkF0#[w'VNo-$,-M&ZdCp7N,8>D8jd?>QH[q,MF+m<-`uj3MW6u8M"
    "*Ks*MUTw78iIp&$uFG)87BqwK7K;xKY'Cp^bIBvLF[`=-dN#<-LN;=-igG<-J5T;-$SIJ&jcH_&]6VSSVlo2DgbgvLbBnR80lOPT^e[k+q:aw'(8Ncs5NR_&$icf`0r(,a1%DGaSD>R*"
    "+.`ca9YZk+OS0F[E'$:)15q-$*^:WJOldI8Krm--9@bw'5i$<-:f,t$m*SW&<fC%MkK3o8AS7Ac^XRT.cGY##:(m<-:7T;-J`/,MPfC%M]KtG%G6(dt,mdEMxw>U*rN*KW%OV9N$v.>-"
    "LN?.%tT*KW[#S/M<B8C%Qd^d+J%Pp7(NHJVP9jp7eTdfVSD>R*T$E_]Yp0F%3e'x9]6&<-TYLq7PMD8AC.1gL6(co7aO*pA-Y`SAuLbA#>)l;-.sL*%>sD:)L`C<-BA,-MCY.R&&_l>R"
    ":vP5MAtXs8i2XMCZMI_/HGu;-DY`=-R&(m8q]TJD9X9/Dnuo,M@uRR&Ivx>@Zt>=9dAUk+<-x;-974W'aP':)ISu;-2DZ&%b+3v6qr#Q8e=i`FOw5F%B/C;$%d_w'Lo&'$A'C4NP%T,M"
    ";A,gL#ImwLlBdwLuScl&0b_R*8s'<-Y3B<&Tjew'g=;:;u(&)tkc4REqa4F%d`@WAF-=c8cj=AYq;O&vxsVxLjBnR8^gtxYSjI,MTv5&:-a9>Z,ex%YG8Uk+B)(v#XU'lX;^quZKj&:)"
    "Vx-_S#98)=Qfl;-%/]I-&/]I-[ml-Mnm[I-*57:MhPW6N6;.&M;E^4Mub?Q%T-n&?isaS8^Fgre;)O,M1OWR%RN$:)BL+WobnJg8hwcof1ZN,M8taS8[w=R*m'iDN8(Pp7AdQV['c2=-"
    "w?t;M(mBK-auc]'aP':)ObPDFKSF,Mrt,A%.pr2;db?Q%8U#:)`dI21Z(m;-($T,MGh]<8wE.&GN]@`]^.v;-loe+%6DT32C'crLK'vhL7ofr6EEx:HDT&:)x5'<-+YqS-Oohx$ODw9)"
    "3XXw9FA7R34aXd4At.>-[SG-MRfK=#_GL_&A;u;-=Z`=-asbP82wIP^_Ymp'/mx#MkK3o8o1+2_W.l,MIS.R&bhu>I7fZTOY1G$M6)>$Mw1K;-:GU5%9.f$'<Tk-$)sp-$&+Fv6Fi<wp"
    "FuTp9BWA?MdNEmL0TLsLWKCsL@0*39AhYSJwl8'-M^_sLU#k_Oi=A?9LK/F.A[M-Q].9R*NIO.?]$F:`,:GW/6M_M#QW*+.'q5tLT0;.MkH_1M@_IU.x(G>#gMZa&WgHU)FZCPg8qn;-"
    "J>QD-7M#<-H7T;-TrbP89P&:)R$g$'Pk5;)VBcw'MUg:),TC_&K.r-$Aj.K<Uem##hfG<-L7T;-b<QD-[$T,M^bu9#wox=#]uv(#$m8Atk7dFP";

