// File: 'pathtag_scan_small.spv' (7872 bytes)
// Exported using binary_to_compressed_c.cpp
static const char pathtag_scan_small_compressed_data_base85[5440+1] =
    "7])#######WKGca'/###$vB8./Dc>#;K?D*F:-##06'N(blZw'T1NP&l50PS)37n9=4in1H)Dq1?(VkLcaKM'Z#p*%SDYm'7(VV$IxIE+<Rd%F4<7rL>_`=-+S,<-*5T;-/5T;-25T;-"
    "75T;-85T;-;5T;-<5T;-=5T;-C5v5M/$S/MK:3NM]@,gL,WO?/P*;LFAH[rLK:#gLOlXU%/%vLFe*?[Ap2JuBw`poDvQDTC7d'oDo#a]A/f@jFfnXw0fSX8&2cWh#/P(:).giTC(:S-7"
    "x4+gL-0M-MbuhP//TKKF-PN_IOGlR*(N_$':.DEHw/]6D?$[v$X.f+MTq6AO4tCrC:$;qL]fC)Nj.gfLJ`:GHLE3kNnLYGMVX1)Nhh7u-b_0HMjYq:Ba8uLFL`Q?S.bZ##tJ'tQk&47/"
    "*)%bHB4J9U=OwA-'(=^-q:&:)/p76DFA]$KCA:b8cZ?D*Q_-?.d07r7IC>R*xd7.Magi/)x.,?./LYGM]Y=W%F####w(B;->@Rm/$<p,GvlpKFS;#-MJ#+fMe:.^Mcq)$#$u@T%*mnmD"
    "p,KkEngjjE&%F(Iw]CEHug)]AD$JT:AROGH2735&D`l_/P4Lh,3_>_/lJSY,rk6<I-Q=7D@+8/G#,1T&#Iw#:)^rTC_/>G-iNp$.#-wiLn7I'&:/>*eGd#&J^06s.K6cmBwswmD5km/O"
    "#/ex-$KNjLBfipLOXQ##%QWjL3:43NPotjL2.]QMURQ##6,l58Z$d*7Zp7Z$bgakF:KC2C%YF&#QJA/;M/]J;K84'G4ieFHve3cHRVh--R&[o@H^VDF<SM=-rg_@-^FI*.0B`QN*Pc)%"
    "Uxe34[iw9)^;S,MBD;=-(mhq7oDat(F0r>$=ow9)P;MqLtt:T./Mc##RN#<-ve66NAXY:CQ#..H^,Lb%vYn6DrTNJV:hpfD9_$Z$+*UYZYG=Z$.1ww0#Tr=B&AQF75`Mb%'j].#34^ih"
    ":hpfD'4HZ$h$tOo8[Q?$1P,##p0USDePPs-x]b[PvdJk&;t<;$tIX&#@*vE7.*k-$j>Me?2`Nh#Adk-$fn'm9(vE#$%f'^#hgv92#w+F%@ak-$>bh>$++m<-Q:m<-/.m<-PRG-MQ_YgL"
    ")KvD-MDIv8M8T;.$Y;F7vxe+M9WvD-CAQ5MK8xiLKPD6MlVG-M-AZ=M;v@Y-#s9I$C^J:)ii':)tLJ_/G)###<@*F7JwC#$>68p&Jf9R3WL:R3=t<;$#95RaVpJF.e#0^OV>.FNH(TZP"
    "@-m<-t>nY%vxe+MiM-+9x'd:;73?:;.V);;L=tY-IA@w^;kwu#++m<-ORG-M2f7iL-_YgL>>b+NKDk+NI8X+NLJt+Na;x/MnP',NGvRiL7E`hL_B,gLB2oiLw1K;-A(m<-+=cH&j;4.-"
    "9cA:)Ff[w'*NC_&#_j-$%ej-$px4kO&N+:)V3Mk+i5g9;I)###VWj-$j0,x'3PA:)g@vu#ok)M-]%.A-:xS,Mcr-A-/fG<-8`/,MuF_1M6qU)N#E5&#l?H*NBS]cO;vRiL(x(hLea./M"
    "`rugL:O.U.G;G##lUwA-vosRN:3%*Na-'CO]W[*Ninl-MU,m<-_9iH-<3@'8,()d*:CG&#vJH&,SjK,*dZv92p9&RN?P[w'xZj-$hSARN?sgJ)V<,REb2iKEIs9W.>;G##Q`]F-3xS,M"
    "vj@iL#xSfLD0;.MZ+m<-_E.FNS7D]PLJt+NkLwA-JrG<-^WC9MMP',N&WP&#$WA,NN3CkL=QrhLJJ=jLlVP&#,&#-NTnl-Mk?9C-Y@;=-K9;.M[OQ-NRvL#8.D*j1>1Xh#c5^G3Vt6x'"
    "x7lp'57m<-h(m<-3.GDNmTNmL,FPGMxMH##?(hhOsB^nL1.gfLOM:@-Z?*RN'a5oL.4pfL/7m<-+)m<-Mr+DN.5voL=x=`N1G;pL+xSfL/7m<-:WDu$BkTJD2[vV%1TRDFc]bDNZ3urL"
    "2h6]O^E:sL6'2hL?BS>-Q)m<-`GPS.8/5###Nk3.39dtL.iG<-_/o3%kUB-mRW&F.MS_:;_AH_&TA,##GR;;$JfH_&i_ucMxBdwLXF6##U.xfLkPG&#QU:xLD*[Q8Mm9>Z4I?v$Vt;Db"
    "qS&'-CFw=N>KI*Nkd:pPl^PWO2WP&#o^?iLW`AN-nx=G-_Pc%Mw.K;-DYlS.t15##EM#<-wO#<-Iiu8.]),##mT6s.:%Xh#G&1I$v,YpBOI)EOQ+q,N.jkjL^*elLLv'kLax5t7A>pV."
    "dF/s7[aeM1N3I21ev*j1t,8)=jcQ9iU%E_&Dmk-$CZJ:)W1a$'-gi*%K9D6NtC_kLbSF0MK[X)#+p/kLKePhL&I(DN[o).NXPqkLsK9C-^mDE-7X;=-mAv5M=pDE-e@;=-a`/,MO8v5M"
    "Gc6lL=&EE-amDE-QU9C-cmDE-8X;=-f)&'.XFB`Nl,elL`tQlLHH`.Mr@9C-m/EE-fmDE-VU9C-hmDE-9X;=-wAv5Mn)E'8S9jV7hN_w0d=@F%0N.;6CQ&:)%t5s7lYM88]&iS8-)b>$"
    "%1,p8J[):)puI59hN_w0ZLpQal*^w'BOg*%o=R;84qbP9<5j*%Fv+>#cldw'-_E<-3.)iL'<l<85-?v$k0C2:rqm;-JTN;&bTo&67I=)#,v8kL>LO3NOFw=N[cl0NNB^nLs)KS%u-F_&"
    "j1m-$Q>l-$v;g_/v0F_&k4m-$o@m-$Wu9)=K,>R*uk.F%HP8_ALms`=uIb&#Hw]w'u-F_&>Cg*%>3+<-$UvD-C=kB-MF7I-l=kB-(gG<-t5T;-K%kB-wM#<-.a/,MHnCH-*mP<-V5T;-"
    "x5T;-0_ZL-l1kB-7GlDNHA2pL+;)pL:Yn>8CL)s@j?]k+PXE8AlFnY6+0cSABtWk+Rk&pASD>R*QaTd+1fipL>[`=-R`uG-4gG<-&6T;-Q`uG-AM;=-ZMk3.dr6qL6C;=-rZYO-ISG-M"
    "uZqS-9mP<-'-CK-LSG-MumwFNt9?LOiZ]C%D#w9)G6qfD;Yb>$MRTGE6oWh#o]ncEbq5)FGWMDF`-m`FA9mcE6t1)Flr5.6eL</HJ5w9)Mmi`FcB*:)>;C<-649s$Q_[:;&a]SNM>w9)"
    "SMbYHZeQk4;Kd:;6W9:;Bw2WJ[HH&8$6^VI4q<<-X;#-MFXX)#3]7R33qKx96?xw9RIDx97Bxw9<^Fx9NgG_&n#MK*KjqsLLnl-MQxP5MBohq7pucG*M%rlKnr3WfUh$R8F5RMLZR72L"
    ".VWh#2H5Wf=pIiLWuoNO]%#OOlSJ_8rcjfM+Ht;-TN#<-.54R-MM#<-X6T;-9@m<-;Nm<-DBm<-SfG<-cNm<-tZ.U..CP##ZgG<-Q6T;-N6T;-:YlS.t7>##f#T,MnU/+MiQwtLYc<uL"
    "W+K7NYjG<->p-A-o)m<->7T;-o=RA-=QF0MNJ=jL?+>DN&7u`:QT:_A],fw'?(')tkc4REu#YF%?7?_8^L[2rYoNuL[tQlLAQrhL[uWuL?8xiL]<*mLJK#8N3oAK%fo`w'L0o-$SlC<-"
    "dmP<-[a/,M[6LS-emP<-ha/,M.Dj*MS1`PO<:'vLfC9vL@nl-Mpc:ENO4gVOOveQ-N*m<-k8Pw$PS-F%Mtb2iJwj>N5P5W-?+F:)Mkf$'gM^G3A-n;%^/,F%Erq-$ij1q9C@7&MFNx>-"
    "ver=-OhG<-MJQD-vrhx$2N,F%elxk+&lt&#d?G##:S,<-f5xU.f;G##vV,hLG]F%tWC'DNRKlDN+?rPOn&<$#@,=8S1Mr--Js_w'CC%<-4I=4%'xnY6C1r;-,ml-M7Hp;->IuG-gT,<-"
    "v/GDNC,VE8,65F%3Owu#6Bcw'L/l-$N7miUOw5F%qo'_]uFaw'g)p-$Mq22US-6F%`8#<-jml-M%Ref&U-g$'F-UJD7oq;-fJIJ&Tjew'E0=:;WS4_J#`/x'h.XpBD7S;%+^q&-T0iH-"
    "+<iH-[oI3%c)%:)7PhY?<=r%chUP`k;kH,MfDE6NedB(MaKt'M]Qw78ZC1AlO8>R*JQx;-%&g?Mpv^(MA_7:.t15##*DkwTM;,##P.LP%nN`;%k/Rd+n.hK-Dkl-M,;hK-7@;=-_Z,5M"
    ",/hK-Fkl-MWRw78a]rS&=B4WSejE88fr7p&JAhJ):B1F.B;u;-Ikl-M8jlP&<`s9)ZF7T.cGY##Nw7>-=@;=-UxS,MCklgL'JsJ%5pC_&D`pDN8(Pp75CIYmWH4=-lsUI&Zrr_]-,'Ka"
    "ENx>-iL>1%./'Ka[#S/Mfa[I-0d+w$Vff2DwVrM8[X%?7cJH)MF[`=-dxS,Mm)='MH<.FNJ`?Q%vO&=(Oh%<-rgG<-Ya/,M5nt)#N7cwLp<ZwL5=LP8OF:&5'<t;-'M#<-WoWo8r(acW"
    "t)w92MR*)XSD>R*nV1F%@S;-mul1F%pDp-$%Sek=*D$<-=pPhLg5-e%&Je$'H)_pT:'o+8B-&)XWC/F.uS?>Z'htxYZMI_/Uxu;-JJDiL.53>5GKo;-+nP<-t`/,MK[X)#X0.#M[nhq7"
    "[1QV[cm4=-_Mu8MZj3g&*BqW8g#Os7uNMS]>2b-?(>T,Mtnhq7-Wio]eNM,MQ<7I->?'D&Gjwk+to;,s5Z]._6,JP^s%?<-Wl./MeNqS-)nl-MAFB`&kmg$'8CUdO')fj8FNUk+q/Ylp"
    "*^7F%A&cY#,BQcsKDUk+3Ad=-L2Vu(@h>xK(B'<-0nl-M#I&k&^3^dO=t.>-Ttb4%$p%:)f's-$3`WGss2I(sI([k+xPdw'*v._SE`3dXIKEn83akM(V%2?%Ya[I-Nkl-Mnm[I-MJY)%"
    "e$oiLLMl;-B@;=-<`/,MVSuD%j15?Iga*s7]$H,*OoD)+=L4F..Z'<-Skl-Mv>ue;Y+)d*[ORW&sBfr8//D)+iPJ,MnQO;.f;G##eu>R*m'iDN8(Pp75Mj(tCb3=-lOJG&Zrr_]-_]&Z"
    "ENx>-d)Qt$.b]&Z[#S/Mfa[I-EK]v$`_HdF4rb48i572Lu'n;-;nl-MRSuD%l,dw'3e'x9eN&<-SrAwPHM6Q:c5bi_PYl;-cFlDNw0G$MK'vhL7ofr68&uF`DT&:)>/u;-/VP5&0STd="
    "5Ac$MT0;.MZDj*M#ZHI8uLUk+@Ubw'+JjcsSue+MAc]F-2[`=-T'(m8*^F&#Ld=<-8f?T-=kl-M)jMb&^<dp0ga*s7twB#$pkG,MYc]F-@kl-Mup0h$tig;-2VDu$&Ar--2X<;$23FR*"
    ":?jDN0R#<-A-OJ-Kai=-57T;-4*fV'KEH:)@9F<-OB,-MH9gN-ec6:&r%I_&/_Ts7F=JucB[R]c@8:Acx=?<-_/C9&2VH;$p@[w'=Yq-$J))_]qifw'14l&#x+,##[vF<-;UZ&%=p,F%"
    "B#cY#tr,F%vIA-ddlq<1CDD_&<m,F%CZJ:)L:t9)W*6;)M=t9)Tkg:),TC_&N@t9)A&-F%0eEs-/q5tLD8xiL^DE6NtRE3MQpcA#wox=#]uv(#$m8AtOYmhL";

