// File: 'pathtag_scan1.spv' (6164 bytes)
// Exported using binary_to_compressed_c.cpp
static const char pathtag_scan1_compressed_data_base85[4210+1] =
    "7])#######OisI)'/####vB8./Dc>#;K?D*1sMcMVEj$#2_e6/.f1$#XsboLIVjN;e/W$H_>Pe3oCA['TxL$#4(gGMMw(hL-:#gLSw3'Mn6T=B.cj*%;kZ;%-XV8&+eR5'0<0j(1EK/)"
    "4aG,*5jcG*6s(d*.*O2(cq:R3a1WU2#w+F%%%?v$7X$Z$6oWh#=J/>B#t[mDJjG<-J9;.M>Rp=B.QOVCK1o:.0Mc##PBD^#U='DN6$DrC,PiEHLJL@->w.>-=?FV.F.EmE'P9C-9_`=-"
    "D-;.Mhh7u-b_0HM(Ar:Ba8uLFkn#[A9ieFH&uR/Gqm*nDp<M=B[5XSMx_:)NGC$##$ExUC(v&$.ce9HM:?DVCqmiTCadsjEQFSXTdRGgLhOU]O*4i*NP,fnT.jRQ-v'=^-q:&:)/p76D"
    "1/*U`?&YE8x4+gL@0Iq77M>R*_ck-MKcrN*g(OpBh07r7e?-Z$Pnhq7]eb&#U.xfL)klgL.TISDrrcdGCpnrL:C;=-S0MeMVZrt--@)78`2(<-q(vhF^0m[A6%&jFqfpoDud[mDI4qHF"
    "(BG/#2`($#^sF?-qPerRkv'w-usMFNYV,jF02DeGYi>iOBx2$#?0h?.)G*_I;;J&#pio;%@]Uw0prJgL/NI2.T]'TMT&]iL80wgFvS>LF?fiF.X^V#$50Mk+*um-$OMuu#x(-F%7-l_&"
    "E2-F%6$Y_&5vES7OREN2RXQ##BIMmL/Kp8%5qF_&s'gS8&EKtq3:u&#,;G##tIVX-j$O-Q+@HZ$pR#29E,k>H$3a]AtpeHd-rF&#@0[G<1xR5B,1Y_&2hF_&'5l/#J;B;IF&O>HApG<-"
    "agG<-26T;-%CsM-*6)t-srg%M4AlFH9*Qt$rEvLg$Z/'-B9_*#nY&gL4o18.Tgf;-3O;=-9RG-M24pfL:O;=-4L;=->X;=-5L;=-P-m-M55RA->@;=-m8WFM0@,gL>dn*NEcsj$w='DN"
    "+u&nLHE;=-PJ:@-#M#<-N`/,MlwQ2MQopcNVC?##CA)d*to=s%2cWh#f;X.-73?:;$8);;L=tY-*(A_8[*iw'=W3kb?u(:)vxX8&:Pgw'AB,.-vxe+MAQrhLW`AN-5M#<-)5T;-J4m<-"
    "D4m<-W_G-Mc6S>-H4m<-V?S>-Cr:T.<;G##(M#<-L`/,MSS559qM&:)JVnA,+)6X1JPUV$bnx],'@n;-cnJ;/)/5##]XbgLw-gfLY*elLoF6##QlRfL@nl-MORGgLV5l?-L9;.MiSF0M"
    "99eAO7SQINU-r)NTnl-MV+m<-XJLw-hq0hL>eZ=M*8V'#N:4R-Y^./MkqIiL9w(hLelk0MN2oiL8qugL.4pfLD0;.M1,m<-QE.FN@W[*NnpJ%#j9_hL,@,gL%R()N#BVhL#xSfLD0;.M"
    "Z+m<-WE.FNLcY[PEv3+NU$iH-QF#-MWmk0MF&=+N&WP&#s,W+NN3CkL6'2hLCvRiLlVP&#%Q8,NTnl-Mk?9C-R@;=-K9;.MT%h,N48`Q&UUt9)ZQQd+RIH-NE8m<-[(m<-RDkGNab6lL"
    "1w?AOf*elL*4pfL^W&%#>CDmLpVP&#HbrmL.iG<-1H^s$Y.v;-RKx>-RJRA-w+D9.,&###)kN>?*lbxu'@n;-86DMN_'=$8N6#'$9_k3N3_:)N)&YgPpuoNOIpDE-lA;=-U9iH-kgG<-"
    "Gtx/..@S?N0*f(#uIZ-HD`[w'95%a+n`McsDbF&,wIF]u?V[A,^]U&5V@'DNa&]iL-2K;-@;^;-5@X,%M%8`&)<EF7D/-F%]sqE@F5-F%Adk-$G]S2`cNEmLTVOjLOu^,NY]XjLtY,oL"
    "4@,gLN1$-NlHp;-3O;=-CB$*Mw.K;-rqF?--^F0MK[X)#$EEjLKePhL&I(DNTD?-NYo`EOVPQ-N.l-AOaUZ-NK=.FNT8LkL[+:kLHH`.Mr@9C-pEw^OYcm-N_78FOGo).N/r6AOft2.N"
    "/r6AOeW$lLaSF0MAdDE-iRG-MA&EE-_mDE-OU9C-amDE-9X;=-pAv5MH^YO-vkl-MqH`.MZ]-lLTaE_OdIs.Nit=GOQU//N1(IAOpZ8/NK=.FNd=*mLk0nlL[6wlL78v5MO=*mL)2K;-"
    "MSB%%ifW_A%fk&#$25##?c^p9dNEmLpH<mLw1K;-gC//.i9_hLmG(HOrM1HOo/#0N,@,gL'$G<8E$(m9b([#6KuKS.rpVG<R,bDNT2aMOPVOjLm<RiP**J:N0B8#Mf+9nLsGG0N..;hL"
    "FcB=#H$AnL%2K;-vcDE-lS,<-j5T;-D(P8MhNEmLW;)pL#M-:;wiF59JSF,MGvRiL;+>DNpDetL=W[*Nd=*mL7%`ENciT=#5Y]F-u[#<-q5S>-0QF0MlA^nL[tQlL:'2hLqGgnL8d7iL"
    "]<*mL`t11NF=S;%%X^w'bol-$pwD<-#mP<-q`/,M[6LS-$mP<-'a/,M.Dj*MiYnIOQc5oL%mGoL2C;=-XA[:M5pDE-nNv5MRt%qLrY8(8ZWlS/6V9Z$^/,F%g@F:)xRO&#Akd.%lh^R*"
    "NM-F%X178%%Ed`O(p0#?DFP8/2&#F@+F0s7G3UJDbZ(&PZMI_/N=h32^=g7NAuLp.dUH;$iVGb%WQo-$vtWv6wN3D<ACg*%lD%+Mae(AMD8MP-R;@YNZm3JOr7S>-NSCq7[vgY?u)N,M"
    ";IS;8#0H;@R<,RExRO&#&GuG-'T,<-6/GDNYZn>8,65F%3Owu#Dl`w'Epk-$eReSAOw5F%M1g-653_w''lm-$d6+s@S-6F%<lBv$f)@>QpL@_8W6J<-sf`=-T*3/%5qI&db1tuLe=0vL"
    "bhP8N'&T,M[sXC.t15##h.XpBD7S;%:4o&-T0iH-:;iH-[oI3%rUx9)x=55T<=r%cx:PPTR?I21bMooSv/B<-%<#-M_ipvLL@7F%noH_&iL#3DsmeQOHv.>-,TG-M'Js*M:d:EN3;11R"
    "4A:1R%b:%M]#k_O*6[=N(v.>-OPsM-IB;=-J`uk-qjQW&S.3J80qm--FSC<->f,t$m*SW&@(i%MkK3o8bxNYd^XRT.cGY##:(m<->7T;-J`/,MT(i%M#JsJ%KB(dt,mdEMxw>U*;U$Ka"
    ",04ROZU^`Ovi%:NHPx>-iL>1%>_$Ka[#S/MX@7F%qjWd4K.l58Gp`cWm8kp7/$&)XSD>R*qw>_f]#1F%3e'x9#6'<-WYLq7pi@5Bi[J88.VWh#A[M-Q=ac3r8=LP8[^+p8&>q;-GSG-M"
    "xU,X&7'c$'I1qp9?wpKO#iipLJNx>-K)O$%u6`_8I>-F%Ybqp96@]qLkdWo8Up5,E.OIp7T-ew'4kE<-YYJs(aXx_J)?p>IV0Z=9k5/F.X,#<-X53Z'aP':)fRv;-QBY)%b+3v6Z^I,M"
    "RqT=#t9p4NBu:T.t=G##H)m<-rTN;&Yb6.-Mk$W]ua;xL*[2xLWJEV&%Ge$'9Khd473Fc8GMUk++kX]Y*^7F%aj.#HW]Uk+4Ca=-l9=w(PA<xKqkv;-@ml-M$N)b&'CZpT=t.>-U#f+%"
    "4I#:)vVp-$3`WGs-nHo[I([k+2+bw'+JjcsSue+M7m_=8L#0;e*_OVe+hkreSD>R*%q08f%sYk+FJQR<SQ$:)C*Xk+].v;-7mSO&Tp`Jsbh&08s5/F..Z'<-eml-MW':T&)#N?.o?>-9"
    "TJv92>OCdO]9R78tRp9r%V9dOQm9H8b,/5^Yqs--9rOP^Y?5F.6%ll^Mt?-Me<.FN)/-A8r55F%Ua@v$8>+2_pSgm8'.FM_cdI21[(m;-,$T,MGh]<8@b*#HkY:`fkP#<-Qlc1%I>-F%"
    "6G,vHK,>R*kVGs-v30sLYw-78u6^VI<5:<-lmg%%RMw9)3XXw9B)(v#3gRd=At.>-_SG-MRfK=#_GL_&Fgei_J1;_AL`C<-aX7?82IBJ`SD>R*2iH<-NhqA&)?p>INJ$.8G4/F.K>BGa"
    "SD>R*xRO&#9<7#%^qIK*c)7:MMUX)#uJ?EMu(k?%BN;F%Lk,wp[1Tn*Eqn-$?J,'?V836N3eiY&Qvc$'V(4x^aY0'?MNx>-A-OJ-`Y`=-QIQD--fpD&/CGW/6M_M#QW*+.*-QtLT0;.M"
    "P(7tLCL,hLK+_=uq*7G;+7@Mh@7k-$_Kn&?RQ^?N2F`hLP3O'M19MhLZSw>%_uWfi=&H,*k(t+jA8dG*<U?v$Wo8Gj6s(d*9+.K<Rem##eS,<-P7T;-b<QD-`$T,Mb$D:#wox=#]uv(#"
    "$m8At7iQ,P";

