


name: C/C++ CI

on:
  push:
    branches: [ wip ]
  pull_request:
    branches: [ wip ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: install dependencies
      shell: bash
      run: |
        sudo apt-get install -y libxinerama-dev libxcursor-dev libxi-dev libxrandr-dev
    
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.3
    - name: run_tests
      run: ./scripts/ci/run_tests.sh
      
      
