


name: C/C++ CI

on:
  push:
    branches: [ wip ]
  pull_request:
    branches: [ wip ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.0.3
    - name: configure
      run: ./scripts/ci/run_tests.sh
      
      
