


name: C/C++ CI

on:
  push:
    branches: [ wip ]
  pull_request:
    branches: [ wip ]

jobs:

  build_windows:
    
    runs-on: windows-latest 
     
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      shell: powershell
      run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/1.2.182.0"
          $Env:Path += ";C:/VulkanSDK/1.2.182.0/Bin"
          function Invoke-Environment {
              param
              (
                 # Any cmd shell command, normally a configuration batch file.
        
                 [Parameter(Mandatory=$true)]
                 [string] $Command
              )    
          
              $Command = "`"" + $Command + "`""
              cmd /c "$Command > nul 2>&1 && set" | . { process {
                if ($_ -match '^([^=]+)=(.*)') {
                  [System.Environment]::SetEnvironmentVariable($matches[1], $matches[2])        
                }
              }}
          }
          Invoke-Environment "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"
          & ./scripts/ci/run_tests.ps1
          
    - name: Setup Vulkan
      run: |
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/1.2.182.0/windows/VulkanSDK-1.2.182.0-Installer.exe" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
    


  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: install dependencies
      shell: bash
      run: 
        sudo apt-get install -y libxinerama-dev libxcursor-dev libxi-dev libxrandr-dev;
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - ;
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.182-focal.list https://packages.lunarg.com/vulkan/1.2.182/lunarg-vulkan-1.2.182-focal.list;
        sudo apt-get -qq update;
        sudo apt-get -y install vulkan-sdk

    - name: Run Tests
      run: ./scripts/ci/run_tests.sh
      
      
